-- Seed data: a realistic slice of the medicines most commonly prescribed in
-- Sri Lankan outpatient practice (government and private). This is a starting
-- formulary for e-prescribing, not a complete national list -- the admin
-- service's content management (SDD §8.8) is the intended place to extend it.

INSERT INTO drugs (name, generic_name, strength, form, manufacturer, category, is_controlled, is_generic) VALUES
    ('Panadol', 'Paracetamol', '500mg', 'tablet', 'GlaxoSmithKline', 'analgesic/antipyretic', FALSE, FALSE),
    ('Paracetamol', 'Paracetamol', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'analgesic/antipyretic', FALSE, TRUE),
    ('Paracetamol Syrup', 'Paracetamol', '120mg/5ml', 'syrup', 'State Pharmaceuticals Corporation', 'analgesic/antipyretic', FALSE, TRUE),
    ('Amoxil', 'Amoxicillin', '500mg', 'capsule', 'GlaxoSmithKline', 'antibiotic', FALSE, FALSE),
    ('Amoxicillin', 'Amoxicillin', '250mg/5ml', 'syrup', 'State Pharmaceuticals Corporation', 'antibiotic', FALSE, TRUE),
    ('Augmentin', 'Co-amoxiclav', '625mg', 'tablet', 'GlaxoSmithKline', 'antibiotic', FALSE, FALSE),
    ('Flagyl', 'Metronidazole', '400mg', 'tablet', 'Sanofi', 'antibiotic', FALSE, FALSE),
    ('Ciprofloxacin', 'Ciprofloxacin', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'antibiotic', FALSE, TRUE),
    ('Azithromycin', 'Azithromycin', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'antibiotic', FALSE, TRUE),
    ('Glucophage', 'Metformin', '500mg', 'tablet', 'Merck', 'antidiabetic', FALSE, FALSE),
    ('Metformin', 'Metformin', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'antidiabetic', FALSE, TRUE),
    ('Diamicron MR', 'Gliclazide', '60mg', 'tablet', 'Servier', 'antidiabetic', FALSE, FALSE),
    ('Amaryl', 'Glimepiride', '2mg', 'tablet', 'Sanofi', 'antidiabetic', FALSE, FALSE),
    ('Lantus', 'Insulin glargine', '100units/ml', 'injection', 'Sanofi', 'antidiabetic', FALSE, FALSE),
    ('Amlodipine', 'Amlodipine', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'antihypertensive', FALSE, TRUE),
    ('Norvasc', 'Amlodipine', '5mg', 'tablet', 'Pfizer', 'antihypertensive', FALSE, FALSE),
    ('Losartan', 'Losartan potassium', '50mg', 'tablet', 'State Pharmaceuticals Corporation', 'antihypertensive', FALSE, TRUE),
    ('Cozaar', 'Losartan potassium', '50mg', 'tablet', 'Merck', 'antihypertensive', FALSE, FALSE),
    ('Enalapril', 'Enalapril maleate', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'antihypertensive', FALSE, TRUE),
    ('Concor', 'Bisoprolol fumarate', '5mg', 'tablet', 'Merck', 'antihypertensive', FALSE, FALSE),
    ('Atorvastatin', 'Atorvastatin calcium', '20mg', 'tablet', 'State Pharmaceuticals Corporation', 'lipid-lowering', FALSE, TRUE),
    ('Lipitor', 'Atorvastatin calcium', '20mg', 'tablet', 'Pfizer', 'lipid-lowering', FALSE, FALSE),
    ('Omeprazole', 'Omeprazole', '20mg', 'capsule', 'State Pharmaceuticals Corporation', 'gastro/PPI', FALSE, TRUE),
    ('Losec', 'Omeprazole', '20mg', 'capsule', 'AstraZeneca', 'gastro/PPI', FALSE, FALSE),
    ('Zantac', 'Ranitidine', '150mg', 'tablet', 'GlaxoSmithKline', 'gastro/H2 blocker', FALSE, FALSE),
    ('Domperidone', 'Domperidone', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'antiemetic', FALSE, TRUE),
    ('Cetirizine', 'Cetirizine hydrochloride', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'antihistamine', FALSE, TRUE),
    ('Piriton', 'Chlorphenamine maleate', '4mg', 'tablet', 'GlaxoSmithKline', 'antihistamine', FALSE, FALSE),
    ('Ventolin', 'Salbutamol', '100mcg/dose', 'inhaler', 'GlaxoSmithKline', 'bronchodilator', FALSE, FALSE),
    ('Salbutamol', 'Salbutamol', '2mg/5ml', 'syrup', 'State Pharmaceuticals Corporation', 'bronchodilator', FALSE, TRUE),
    ('Seretide', 'Fluticasone/Salmeterol', '25/125mcg', 'inhaler', 'GlaxoSmithKline', 'bronchodilator/steroid', FALSE, FALSE),
    ('Prednisolone', 'Prednisolone', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'corticosteroid', FALSE, TRUE),
    ('Betnovate', 'Betamethasone valerate', '0.1%', 'cream', 'GlaxoSmithKline', 'topical corticosteroid', FALSE, FALSE),
    ('Diclofenac', 'Diclofenac sodium', '50mg', 'tablet', 'State Pharmaceuticals Corporation', 'NSAID', FALSE, TRUE),
    ('Voltaren', 'Diclofenac sodium', '50mg', 'tablet', 'Novartis', 'NSAID', FALSE, FALSE),
    ('Ibuprofen', 'Ibuprofen', '400mg', 'tablet', 'State Pharmaceuticals Corporation', 'NSAID', FALSE, TRUE),
    ('Tramadol', 'Tramadol hydrochloride', '50mg', 'capsule', 'State Pharmaceuticals Corporation', 'analgesic (opioid)', TRUE, TRUE),
    ('Diazepam', 'Diazepam', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'anxiolytic', TRUE, TRUE),
    ('Alprazolam', 'Alprazolam', '0.25mg', 'tablet', 'State Pharmaceuticals Corporation', 'anxiolytic', TRUE, TRUE),
    ('ORS', 'Oral Rehydration Salts', 'WHO formula', 'sachet', 'State Pharmaceuticals Corporation', 'rehydration', FALSE, TRUE),
    ('Folic Acid', 'Folic acid', '5mg', 'tablet', 'State Pharmaceuticals Corporation', 'vitamin/supplement', FALSE, TRUE),
    ('Iberet Folic', 'Ferrous sulphate/Folic acid', '105mg/0.35mg', 'tablet', 'Abbott', 'vitamin/supplement', FALSE, FALSE),
    ('Calcium Carbonate', 'Calcium carbonate', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'vitamin/supplement', FALSE, TRUE),
    ('Metoclopramide', 'Metoclopramide', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'antiemetic', FALSE, TRUE),
    ('Loratadine', 'Loratadine', '10mg', 'tablet', 'State Pharmaceuticals Corporation', 'antihistamine', FALSE, TRUE),
    ('Cefuroxime', 'Cefuroxime axetil', '500mg', 'tablet', 'State Pharmaceuticals Corporation', 'antibiotic', FALSE, TRUE),
    ('Doxycycline', 'Doxycycline', '100mg', 'capsule', 'State Pharmaceuticals Corporation', 'antibiotic', FALSE, TRUE),
    ('Aspirin', 'Acetylsalicylic acid', '75mg', 'tablet', 'State Pharmaceuticals Corporation', 'antiplatelet', FALSE, TRUE),
    ('Clopidogrel', 'Clopidogrel', '75mg', 'tablet', 'State Pharmaceuticals Corporation', 'antiplatelet', FALSE, TRUE);
