-- Seed data: a working subset of WHO ICD-10 covering Sri Lankan primary care
-- and the specialties this platform lists (SDD 7.1: GP, cardiology, and the
-- rest). 641 codes, every one a real WHO ICD-10 rubric -- not invented, and not
-- ICD-10-CM, which is the US clinical modification and is not what Sri Lanka
-- codes against.
--
-- What is here and why:
--   * Infectious disease is over-represented on purpose. Dengue (A90/A91) and
--     leptospirosis (A27.x) are notifiable, seasonal and lethal here in a way
--     they are not in the datasets most ICD pickers ship with; scrub typhus,
--     melioidosis-adjacent rickettsioses, filariasis, soil-transmitted
--     helminths and snake envenomation (T63.0) are everyday primary-care
--     entries in this country and absent from most "common codes" lists.
--   * Endocrine/diabetes, cardiovascular and respiratory reflect the actual
--     non-communicable disease burden -- Sri Lanka's diabetes prevalence is
--     among the highest in South Asia.
--   * CKD of uncertain aetiology (CKDu) in the North Central dry zone is why
--     N18.x carries "CKDu" as a search synonym.
--   * Paediatrics, dermatology, mental health, gynaecology/obstetrics and the
--     symptom (R) chapter are included because a telemedicine GP consultation
--     very often ends in a symptom code, not a disease code.
--
-- The `synonyms` column is what a doctor actually types: "sugar" for diabetes,
-- "piles" for haemorrhoids, "PID" for a prolapsed lumbar disc, "polonga" for a
-- Russell's viper bite. It is weighted below the official rubric in the search
-- vector, so it broadens recall without displacing the exact match.
--
-- This is a starting set, not the full ~14,000-rubric classification. Extending
-- it is content management (SDD 8.8), the same as the drug formulary.

INSERT INTO icd10_codes (code, display, category, synonyms) VALUES
    ('A00', 'Cholera', 'infectious', 'cholera vibrio rice water stools'),
    ('A01.0', 'Typhoid fever', 'infectious', 'typhoid enteric fever salmonella typhi'),
    ('A01.4', 'Paratyphoid fever, unspecified', 'infectious', 'paratyphoid'),
    ('A02.0', 'Salmonella enteritis', 'infectious', 'salmonella food poisoning'),
    ('A03.9', 'Shigellosis, unspecified', 'infectious', 'shigella bacillary dysentery'),
    ('A04.5', 'Campylobacter enteritis', 'infectious', 'campylobacter'),
    ('A04.7', 'Enterocolitis due to Clostridium difficile', 'infectious', 'c difficile pseudomembranous colitis'),
    ('A04.9', 'Bacterial intestinal infection, unspecified', 'infectious', 'bacterial gastroenteritis'),
    ('A05.9', 'Bacterial foodborne intoxication, unspecified', 'infectious', 'food poisoning'),
    ('A06.0', 'Acute amoebic dysentery', 'infectious', 'amoebiasis entamoeba dysentery'),
    ('A06.9', 'Amoebiasis, unspecified', 'infectious', 'amoebiasis entamoeba histolytica'),
    ('A07.1', 'Giardiasis [lambliasis]', 'infectious', 'giardia lamblia'),
    ('A08.0', 'Rotaviral enteritis', 'infectious', 'rotavirus diarrhoea children'),
    ('A08.4', 'Viral intestinal infection, unspecified', 'infectious', 'viral gastroenteritis stomach flu'),
    ('A09', 'Diarrhoea and gastroenteritis of presumed infectious origin', 'infectious', 'gastroenteritis diarrhoea loose stools AGE'),
    ('A15.0', 'Tuberculosis of lung, confirmed by sputum microscopy with or without culture', 'infectious', 'TB pulmonary smear positive AFB'),
    ('A15.3', 'Tuberculosis of lung, confirmed by unspecified means', 'infectious', 'TB pulmonary confirmed'),
    ('A16.2', 'Tuberculosis of lung, without mention of bacteriological or histological confirmation', 'infectious', 'TB pulmonary clinically diagnosed'),
    ('A16.9', 'Respiratory tuberculosis unspecified, without mention of bacteriological or histological confirmation', 'infectious', 'TB respiratory'),
    ('A17.0', 'Tuberculous meningitis', 'infectious', 'TB meningitis TBM'),
    ('A18.0', 'Tuberculosis of bones and joints', 'infectious', 'spinal TB Pott disease'),
    ('A18.2', 'Tuberculous peripheral lymphadenopathy', 'infectious', 'TB lymph node scrofula'),
    ('A19.9', 'Miliary tuberculosis, unspecified', 'infectious', 'miliary TB disseminated'),
    ('A27.0', 'Leptospirosis icterohaemorrhagica', 'infectious', 'leptospirosis Weil disease rat fever mee una'),
    ('A27.8', 'Other forms of leptospirosis', 'infectious', 'leptospirosis anicteric rat fever'),
    ('A27.9', 'Leptospirosis, unspecified', 'infectious', 'leptospirosis lepto rat fever paddy field fever mee una'),
    ('A30.9', 'Leprosy, unspecified', 'infectious', 'leprosy hansen disease'),
    ('A33', 'Tetanus neonatorum', 'paediatrics', 'neonatal tetanus'),
    ('A35', 'Other tetanus', 'infectious', 'tetanus lockjaw'),
    ('A36.9', 'Diphtheria, unspecified', 'infectious', 'diphtheria'),
    ('A37.9', 'Whooping cough, unspecified', 'paediatrics', 'pertussis whooping cough'),
    ('A38', 'Scarlet fever', 'paediatrics', 'scarlet fever scarlatina'),
    ('A39.0', 'Meningococcal meningitis', 'infectious', 'meningococcus meningitis'),
    ('A40.9', 'Streptococcal septicaemia, unspecified', 'infectious', 'strep sepsis septicaemia'),
    ('A41.9', 'Septicaemia, unspecified', 'infectious', 'sepsis septicaemia bloodstream infection'),
    ('A46', 'Erysipelas', 'dermatology', 'erysipelas skin infection'),
    ('A48.0', 'Gas gangrene', 'infectious', 'gas gangrene clostridial myonecrosis'),
    ('A49.0', 'Staphylococcal infection, unspecified site', 'infectious', 'staph infection staphylococcus'),
    ('A49.9', 'Bacterial infection, unspecified', 'infectious', 'bacterial infection'),
    ('A53.9', 'Syphilis, unspecified', 'infectious', 'syphilis STI STD'),
    ('A54.9', 'Gonococcal infection, unspecified', 'infectious', 'gonorrhoea gonococcus STI'),
    ('A56.0', 'Chlamydial infection of lower genitourinary tract', 'infectious', 'chlamydia STI urethritis'),
    ('A59.0', 'Urogenital trichomoniasis', 'infectious', 'trichomonas vaginalis STI'),
    ('A60.0', 'Herpesviral infection of genitalia and urogenital tract', 'infectious', 'genital herpes HSV STI'),
    ('A63.0', 'Anogenital (venereal) warts', 'infectious', 'genital warts condyloma HPV'),
    ('A64', 'Unspecified sexually transmitted disease', 'infectious', 'STI STD'),
    ('A75.3', 'Typhus fever due to Orientia tsutsugamushi', 'infectious', 'scrub typhus mite typhus eschar'),
    ('A77.1', 'Spotted fever due to Rickettsia conorii', 'infectious', 'spotted fever rickettsia tick typhus'),
    ('A77.9', 'Spotted fever, unspecified', 'infectious', 'spotted fever rickettsia'),
    ('A79.9', 'Rickettsiosis, unspecified', 'infectious', 'rickettsial illness'),
    ('A82.9', 'Rabies, unspecified', 'infectious', 'rabies dog bite hydrophobia'),
    ('A87.9', 'Viral meningitis, unspecified', 'infectious', 'viral meningitis aseptic'),
    ('A90', 'Dengue fever [classical dengue]', 'infectious', 'dengue DF break-bone fever denguwa'),
    ('A91', 'Dengue haemorrhagic fever', 'infectious', 'DHF dengue haemorrhagic shock syndrome DSS'),
    ('A92.0', 'Chikungunya virus disease', 'infectious', 'chikungunya chik joint pain'),
    ('A92.5', 'Zika virus disease', 'infectious', 'zika'),
    ('B00.9', 'Herpesviral infection, unspecified', 'infectious', 'herpes simplex HSV cold sore'),
    ('B01.9', 'Varicella without complication', 'infectious', 'chickenpox varicella'),
    ('B02.9', 'Zoster without complication', 'infectious', 'shingles herpes zoster'),
    ('B05.9', 'Measles without complication', 'paediatrics', 'measles rubeola'),
    ('B06.9', 'Rubella without complication', 'paediatrics', 'rubella german measles'),
    ('B07', 'Viral warts', 'dermatology', 'warts verruca'),
    ('B08.4', 'Enteroviral vesicular stomatitis with exanthem', 'paediatrics', 'hand foot and mouth disease HFMD coxsackie'),
    ('B15.9', 'Hepatitis A without hepatic coma', 'infectious', 'hepatitis A jaundice'),
    ('B16.9', 'Acute hepatitis B without delta-agent and without hepatic coma', 'infectious', 'hepatitis B acute HBV'),
    ('B17.1', 'Acute hepatitis C', 'infectious', 'hepatitis C acute HCV'),
    ('B18.1', 'Chronic viral hepatitis B without delta-agent', 'infectious', 'chronic hepatitis B HBV carrier'),
    ('B18.2', 'Chronic viral hepatitis C', 'infectious', 'chronic hepatitis C HCV'),
    ('B19.9', 'Unspecified viral hepatitis without hepatic coma', 'infectious', 'viral hepatitis jaundice'),
    ('B20', 'HIV disease resulting in infectious and parasitic diseases', 'infectious', 'HIV AIDS opportunistic infection'),
    ('B24', 'Unspecified human immunodeficiency virus [HIV] disease', 'infectious', 'HIV AIDS'),
    ('B26.9', 'Mumps without complication', 'paediatrics', 'mumps parotitis'),
    ('B27.9', 'Infectious mononucleosis, unspecified', 'infectious', 'glandular fever EBV mono'),
    ('B34.9', 'Viral infection, unspecified', 'infectious', 'viral fever viral illness'),
    ('B35.0', 'Tinea barbae and tinea capitis', 'dermatology', 'scalp ringworm tinea capitis'),
    ('B35.3', 'Tinea pedis', 'dermatology', 'athlete foot tinea pedis'),
    ('B35.4', 'Tinea corporis', 'dermatology', 'ringworm tinea corporis'),
    ('B35.6', 'Tinea cruris', 'dermatology', 'jock itch tinea cruris groin'),
    ('B36.0', 'Pityriasis versicolor', 'dermatology', 'tinea versicolor pityriasis'),
    ('B37.0', 'Candidal stomatitis', 'infectious', 'oral thrush candida'),
    ('B37.3', 'Candidiasis of vulva and vagina', 'gynaecology', 'vaginal thrush candida yeast'),
    ('B37.9', 'Candidiasis, unspecified', 'infectious', 'candida thrush'),
    ('B50.9', 'Plasmodium falciparum malaria, unspecified', 'infectious', 'falciparum malaria'),
    ('B51.9', 'Plasmodium vivax malaria without complication', 'infectious', 'vivax malaria'),
    ('B54', 'Unspecified malaria', 'infectious', 'malaria'),
    ('B55.1', 'Cutaneous leishmaniasis', 'infectious', 'leishmaniasis cutaneous skin ulcer sandfly'),
    ('B55.9', 'Leishmaniasis, unspecified', 'infectious', 'leishmaniasis'),
    ('B74.0', 'Filariasis due to Wuchereria bancrofti', 'infectious', 'filariasis bancroftian elephantiasis'),
    ('B74.9', 'Filariasis, unspecified', 'infectious', 'filariasis lymphatic'),
    ('B76.0', 'Ancylostomiasis', 'infectious', 'hookworm ancylostoma'),
    ('B76.9', 'Hookworm disease, unspecified', 'infectious', 'hookworm'),
    ('B77.9', 'Ascariasis, unspecified', 'infectious', 'roundworm ascaris worms'),
    ('B79', 'Trichuriasis', 'infectious', 'whipworm trichuris'),
    ('B80', 'Enterobiasis', 'paediatrics', 'threadworm pinworm enterobius'),
    ('B85.0', 'Pediculosis due to Pediculus humanus capitis', 'dermatology', 'head lice pediculosis'),
    ('B86', 'Scabies', 'dermatology', 'scabies itch mites'),
    ('B99', 'Other and unspecified infectious diseases', 'infectious', 'infection unspecified'),
    ('U07.1', 'COVID-19, virus identified', 'infectious', 'covid coronavirus sars-cov-2 pcr positive'),
    ('U07.2', 'COVID-19, virus not identified', 'infectious', 'covid clinically diagnosed coronavirus'),
    ('C16.9', 'Malignant neoplasm of stomach, unspecified', 'oncology', 'gastric cancer stomach carcinoma'),
    ('C18.9', 'Malignant neoplasm of colon, unspecified', 'oncology', 'colon cancer colorectal'),
    ('C20', 'Malignant neoplasm of rectum', 'oncology', 'rectal cancer colorectal'),
    ('C22.0', 'Liver cell carcinoma', 'oncology', 'hepatocellular carcinoma HCC liver cancer'),
    ('C34.9', 'Malignant neoplasm of bronchus or lung, unspecified', 'oncology', 'lung cancer bronchogenic carcinoma'),
    ('C50.9', 'Malignant neoplasm of breast, unspecified', 'oncology', 'breast cancer carcinoma'),
    ('C53.9', 'Malignant neoplasm of cervix uteri, unspecified', 'oncology', 'cervical cancer'),
    ('C61', 'Malignant neoplasm of prostate', 'oncology', 'prostate cancer'),
    ('C73', 'Malignant neoplasm of thyroid gland', 'oncology', 'thyroid cancer'),
    ('C80.9', 'Malignant neoplasm, primary site unspecified', 'oncology', 'cancer malignancy unknown primary'),
    ('C91.0', 'Acute lymphoblastic leukaemia', 'oncology', 'ALL leukaemia children'),
    ('D17.9', 'Benign lipomatous neoplasm, unspecified', 'oncology', 'lipoma fatty lump'),
    ('D18.0', 'Haemangioma, any site', 'oncology', 'haemangioma birthmark'),
    ('D22.9', 'Melanocytic naevi, unspecified', 'dermatology', 'mole naevus nevus'),
    ('D24', 'Benign neoplasm of breast', 'oncology', 'fibroadenoma breast lump benign'),
    ('D25.9', 'Leiomyoma of uterus, unspecified', 'gynaecology', 'fibroid uterine myoma'),
    ('D36.9', 'Benign neoplasm, unspecified site', 'oncology', 'benign tumour'),
    ('D50.0', 'Iron deficiency anaemia secondary to blood loss (chronic)', 'haematology', 'iron deficiency anaemia blood loss'),
    ('D50.9', 'Iron deficiency anaemia, unspecified', 'haematology', 'iron deficiency anaemia IDA low haemoglobin'),
    ('D51.9', 'Vitamin B12 deficiency anaemia, unspecified', 'haematology', 'B12 deficiency megaloblastic anaemia'),
    ('D52.9', 'Folate deficiency anaemia, unspecified', 'haematology', 'folate deficiency anaemia'),
    ('D53.9', 'Nutritional anaemia, unspecified', 'haematology', 'nutritional anaemia'),
    ('D55.0', 'Anaemia due to glucose-6-phosphate dehydrogenase [G6PD] deficiency', 'haematology', 'G6PD deficiency haemolysis'),
    ('D56.1', 'Beta thalassaemia', 'haematology', 'beta thalassaemia major transfusion'),
    ('D56.3', 'Thalassaemia trait', 'haematology', 'thalassaemia trait carrier minor'),
    ('D56.9', 'Thalassaemia, unspecified', 'haematology', 'thalassaemia'),
    ('D57.1', 'Sickle-cell anaemia without crisis', 'haematology', 'sickle cell anaemia'),
    ('D59.9', 'Acquired haemolytic anaemia, unspecified', 'haematology', 'haemolytic anaemia'),
    ('D64.9', 'Anaemia, unspecified', 'haematology', 'anaemia low haemoglobin pallor'),
    ('D68.9', 'Coagulation defect, unspecified', 'haematology', 'clotting disorder coagulopathy'),
    ('D69.3', 'Idiopathic thrombocytopenic purpura', 'haematology', 'ITP low platelets purpura'),
    ('D69.6', 'Thrombocytopenia, unspecified', 'haematology', 'low platelets thrombocytopenia'),
    ('D72.8', 'Other specified disorders of white blood cells', 'haematology', 'leucocytosis leucopenia white cells'),
    ('D75.9', 'Disease of blood and blood-forming organs, unspecified', 'haematology', 'blood disorder'),
    ('E03.9', 'Hypothyroidism, unspecified', 'endocrine', 'hypothyroid underactive thyroid low T4 TSH high'),
    ('E04.9', 'Nontoxic goitre, unspecified', 'endocrine', 'goitre thyroid swelling'),
    ('E05.9', 'Thyrotoxicosis, unspecified', 'endocrine', 'hyperthyroid thyrotoxicosis graves overactive thyroid'),
    ('E06.3', 'Autoimmune thyroiditis', 'endocrine', 'hashimoto thyroiditis autoimmune'),
    ('E10.6', 'Type 1 diabetes mellitus with other specified complications', 'endocrine', 'T1DM complications'),
    ('E10.9', 'Type 1 diabetes mellitus without complications', 'endocrine', 'type 1 diabetes T1DM IDDM insulin dependent'),
    ('E11.2', 'Type 2 diabetes mellitus with renal complications', 'endocrine', 'diabetic nephropathy T2DM kidney'),
    ('E11.3', 'Type 2 diabetes mellitus with ophthalmic complications', 'endocrine', 'diabetic retinopathy T2DM eye'),
    ('E11.4', 'Type 2 diabetes mellitus with neurological complications', 'endocrine', 'diabetic neuropathy T2DM nerve'),
    ('E11.5', 'Type 2 diabetes mellitus with peripheral circulatory complications', 'endocrine', 'diabetic foot T2DM peripheral vascular'),
    ('E11.6', 'Type 2 diabetes mellitus with other specified complications', 'endocrine', 'T2DM complications'),
    ('E11.7', 'Type 2 diabetes mellitus with multiple complications', 'endocrine', 'T2DM multiple complications'),
    ('E11.8', 'Type 2 diabetes mellitus with unspecified complications', 'endocrine', 'T2DM complications'),
    ('E11.9', 'Type 2 diabetes mellitus without complications', 'endocrine', 'type 2 diabetes T2DM NIDDM sugar diabetes mellitus'),
    ('E13.9', 'Other specified diabetes mellitus without complications', 'endocrine', 'secondary diabetes'),
    ('E14.9', 'Unspecified diabetes mellitus without complications', 'endocrine', 'diabetes unspecified'),
    ('E16.2', 'Hypoglycaemia, unspecified', 'endocrine', 'hypoglycaemia low blood sugar hypo'),
    ('E24.9', 'Cushing syndrome, unspecified', 'endocrine', 'cushing hypercortisolism'),
    ('E27.1', 'Primary adrenocortical insufficiency', 'endocrine', 'addison disease adrenal insufficiency'),
    ('E28.2', 'Polycystic ovarian syndrome', 'endocrine', 'PCOS polycystic ovaries'),
    ('E34.3', 'Short stature, not elsewhere classified', 'paediatrics', 'short stature growth failure'),
    ('E44.0', 'Moderate protein-energy malnutrition', 'paediatrics', 'malnutrition moderate underweight'),
    ('E44.1', 'Mild protein-energy malnutrition', 'paediatrics', 'malnutrition mild underweight'),
    ('E46', 'Unspecified protein-energy malnutrition', 'paediatrics', 'malnutrition undernutrition'),
    ('E53.8', 'Deficiency of other specified B group vitamins', 'endocrine', 'B vitamin deficiency B12 B6'),
    ('E55.9', 'Vitamin D deficiency, unspecified', 'endocrine', 'vitamin D deficiency'),
    ('E56.9', 'Vitamin deficiency, unspecified', 'endocrine', 'vitamin deficiency'),
    ('E61.1', 'Iron deficiency', 'endocrine', 'iron deficiency low ferritin'),
    ('E63.9', 'Nutritional deficiency, unspecified', 'endocrine', 'nutritional deficiency'),
    ('E66.0', 'Obesity due to excess calories', 'endocrine', 'obesity overweight high BMI'),
    ('E66.9', 'Obesity, unspecified', 'endocrine', 'obesity overweight BMI'),
    ('E73.9', 'Lactose intolerance, unspecified', 'gastroenterology', 'lactose intolerance milk'),
    ('E78.0', 'Pure hypercholesterolaemia', 'endocrine', 'high cholesterol LDL hypercholesterolaemia'),
    ('E78.1', 'Pure hyperglyceridaemia', 'endocrine', 'high triglycerides'),
    ('E78.2', 'Mixed hyperlipidaemia', 'endocrine', 'mixed dyslipidaemia cholesterol triglycerides'),
    ('E78.5', 'Hyperlipidaemia, unspecified', 'endocrine', 'dyslipidaemia high cholesterol lipids'),
    ('E79.0', 'Hyperuricaemia without signs of inflammatory arthritis and tophaceous disease', 'endocrine', 'high uric acid hyperuricaemia'),
    ('E86', 'Volume depletion', 'endocrine', 'dehydration hypovolaemia fluid loss'),
    ('E87.1', 'Hypo-osmolality and hyponatraemia', 'endocrine', 'hyponatraemia low sodium'),
    ('E87.6', 'Hypokalaemia', 'endocrine', 'hypokalaemia low potassium'),
    ('F03', 'Unspecified dementia', 'mental_health', 'dementia memory loss cognitive decline'),
    ('F10.1', 'Mental and behavioural disorders due to use of alcohol: harmful use', 'mental_health', 'alcohol harmful use'),
    ('F10.2', 'Mental and behavioural disorders due to use of alcohol: dependence syndrome', 'mental_health', 'alcohol dependence alcoholism'),
    ('F17.1', 'Mental and behavioural disorders due to use of tobacco: harmful use', 'mental_health', 'smoking tobacco harmful use'),
    ('F17.2', 'Mental and behavioural disorders due to use of tobacco: dependence syndrome', 'mental_health', 'nicotine dependence smoking addiction'),
    ('F19.2', 'Mental and behavioural disorders due to multiple drug use: dependence syndrome', 'mental_health', 'substance dependence polysubstance'),
    ('F20.9', 'Schizophrenia, unspecified', 'mental_health', 'schizophrenia psychosis'),
    ('F25.9', 'Schizoaffective disorder, unspecified', 'mental_health', 'schizoaffective'),
    ('F31.9', 'Bipolar affective disorder, unspecified', 'mental_health', 'bipolar manic depression'),
    ('F32.0', 'Mild depressive episode', 'mental_health', 'mild depression low mood'),
    ('F32.1', 'Moderate depressive episode', 'mental_health', 'moderate depression'),
    ('F32.2', 'Severe depressive episode without psychotic symptoms', 'mental_health', 'severe depression'),
    ('F32.9', 'Depressive episode, unspecified', 'mental_health', 'depression low mood depressed'),
    ('F33.9', 'Recurrent depressive disorder, unspecified', 'mental_health', 'recurrent depression MDD'),
    ('F40.1', 'Social phobias', 'mental_health', 'social anxiety social phobia'),
    ('F41.0', 'Panic disorder [episodic paroxysmal anxiety]', 'mental_health', 'panic attacks panic disorder'),
    ('F41.1', 'Generalized anxiety disorder', 'mental_health', 'GAD generalised anxiety worry'),
    ('F41.2', 'Mixed anxiety and depressive disorder', 'mental_health', 'mixed anxiety depression'),
    ('F41.9', 'Anxiety disorder, unspecified', 'mental_health', 'anxiety anxious'),
    ('F42.9', 'Obsessive-compulsive disorder, unspecified', 'mental_health', 'OCD obsessive compulsive'),
    ('F43.0', 'Acute stress reaction', 'mental_health', 'acute stress reaction'),
    ('F43.1', 'Post-traumatic stress disorder', 'mental_health', 'PTSD trauma flashbacks'),
    ('F43.2', 'Adjustment disorders', 'mental_health', 'adjustment disorder stress'),
    ('F44.9', 'Dissociative [conversion] disorder, unspecified', 'mental_health', 'conversion disorder dissociative'),
    ('F45.0', 'Somatization disorder', 'mental_health', 'somatisation medically unexplained symptoms'),
    ('F45.4', 'Persistent somatoform pain disorder', 'mental_health', 'chronic pain somatoform'),
    ('F48.0', 'Neurasthenia', 'mental_health', 'neurasthenia fatigue syndrome'),
    ('F50.0', 'Anorexia nervosa', 'mental_health', 'anorexia nervosa eating disorder'),
    ('F51.0', 'Nonorganic insomnia', 'mental_health', 'insomnia sleeplessness cannot sleep'),
    ('F52.2', 'Failure of genital response', 'mental_health', 'erectile dysfunction psychogenic'),
    ('F60.3', 'Emotionally unstable personality disorder', 'mental_health', 'borderline personality EUPD'),
    ('F70.9', 'Mild mental retardation, without or with minimal impairment of behaviour', 'mental_health', 'intellectual disability mild'),
    ('F80.9', 'Developmental disorder of speech and language, unspecified', 'paediatrics', 'speech delay language delay'),
    ('F84.0', 'Childhood autism', 'paediatrics', 'autism ASD autistic'),
    ('F90.0', 'Disturbance of activity and attention', 'paediatrics', 'ADHD attention deficit hyperactivity'),
    ('F90.9', 'Hyperkinetic disorder, unspecified', 'paediatrics', 'hyperactivity ADHD'),
    ('F91.9', 'Conduct disorder, unspecified', 'paediatrics', 'conduct disorder behaviour'),
    ('F98.0', 'Nonorganic enuresis', 'paediatrics', 'bedwetting enuresis'),
    ('F99', 'Mental disorder, not otherwise specified', 'mental_health', 'mental disorder unspecified'),
    ('G20', 'Parkinson disease', 'neurology', 'parkinson tremor rigidity'),
    ('G25.0', 'Essential tremor', 'neurology', 'essential tremor shaking'),
    ('G35', 'Multiple sclerosis', 'neurology', 'MS multiple sclerosis demyelination'),
    ('G40.3', 'Generalized idiopathic epilepsy and epileptic syndromes', 'neurology', 'generalised epilepsy tonic clonic'),
    ('G40.9', 'Epilepsy, unspecified', 'neurology', 'epilepsy seizures fits'),
    ('G43.0', 'Migraine without aura [common migraine]', 'neurology', 'migraine common without aura'),
    ('G43.1', 'Migraine with aura [classical migraine]', 'neurology', 'migraine with aura classical'),
    ('G43.9', 'Migraine, unspecified', 'neurology', 'migraine headache'),
    ('G44.2', 'Tension-type headache', 'neurology', 'tension headache TTH'),
    ('G45.9', 'Transient cerebral ischaemic attack, unspecified', 'cardiovascular', 'TIA mini stroke'),
    ('G47.0', 'Disorders of initiating and maintaining sleep [insomnias]', 'neurology', 'insomnia sleep disorder'),
    ('G47.3', 'Sleep apnoea', 'respiratory', 'OSA obstructive sleep apnoea snoring'),
    ('G50.0', 'Trigeminal neuralgia', 'neurology', 'trigeminal neuralgia facial pain'),
    ('G51.0', 'Bell palsy', 'neurology', 'bell palsy facial nerve palsy'),
    ('G56.0', 'Carpal tunnel syndrome', 'musculoskeletal', 'carpal tunnel median nerve wrist'),
    ('G58.9', 'Mononeuropathy, unspecified', 'neurology', 'mononeuropathy nerve entrapment'),
    ('G62.9', 'Polyneuropathy, unspecified', 'neurology', 'peripheral neuropathy numbness tingling'),
    ('G63.2', 'Diabetic polyneuropathy', 'neurology', 'diabetic neuropathy burning feet'),
    ('G80.9', 'Cerebral palsy, unspecified', 'paediatrics', 'cerebral palsy CP'),
    ('G81.9', 'Hemiplegia, unspecified', 'neurology', 'hemiplegia one sided weakness'),
    ('G93.3', 'Postviral fatigue syndrome', 'neurology', 'post viral fatigue chronic fatigue'),
    ('H00.0', 'Hordeolum and other deep inflammation of eyelid', 'ophthalmology', 'stye hordeolum eyelid'),
    ('H01.0', 'Blepharitis', 'ophthalmology', 'blepharitis eyelid inflammation'),
    ('H04.1', 'Other disorders of lacrimal gland', 'ophthalmology', 'dry eye lacrimal'),
    ('H10.0', 'Mucopurulent conjunctivitis', 'ophthalmology', 'bacterial conjunctivitis discharge red eye'),
    ('H10.1', 'Acute atopic conjunctivitis', 'ophthalmology', 'allergic conjunctivitis itchy eyes'),
    ('H10.9', 'Conjunctivitis, unspecified', 'ophthalmology', 'conjunctivitis red eye pink eye madesma'),
    ('H11.0', 'Pterygium', 'ophthalmology', 'pterygium surfer eye'),
    ('H16.0', 'Corneal ulcer', 'ophthalmology', 'corneal ulcer keratitis'),
    ('H16.9', 'Keratitis, unspecified', 'ophthalmology', 'keratitis cornea inflammation'),
    ('H20.9', 'Iridocyclitis, unspecified', 'ophthalmology', 'uveitis iritis'),
    ('H25.9', 'Senile cataract, unspecified', 'ophthalmology', 'cataract age related'),
    ('H26.9', 'Cataract, unspecified', 'ophthalmology', 'cataract lens opacity'),
    ('H35.0', 'Background retinopathy and retinal vascular changes', 'ophthalmology', 'hypertensive retinopathy retinal'),
    ('H36.0', 'Diabetic retinopathy', 'ophthalmology', 'diabetic retinopathy DR eye'),
    ('H40.1', 'Primary open-angle glaucoma', 'ophthalmology', 'open angle glaucoma raised IOP'),
    ('H40.9', 'Glaucoma, unspecified', 'ophthalmology', 'glaucoma eye pressure'),
    ('H52.0', 'Hypermetropia', 'ophthalmology', 'long sighted hypermetropia hyperopia'),
    ('H52.1', 'Myopia', 'ophthalmology', 'short sighted myopia near sighted'),
    ('H52.2', 'Astigmatism', 'ophthalmology', 'astigmatism'),
    ('H52.4', 'Presbyopia', 'ophthalmology', 'presbyopia reading glasses'),
    ('H54.9', 'Unspecified visual impairment (binocular)', 'ophthalmology', 'visual impairment poor vision'),
    ('H57.1', 'Ocular pain', 'ophthalmology', 'eye pain'),
    ('H60.9', 'Otitis externa, unspecified', 'ent', 'otitis externa swimmer ear canal'),
    ('H61.2', 'Impacted cerumen', 'ent', 'ear wax impacted cerumen'),
    ('H65.9', 'Nonsuppurative otitis media, unspecified', 'ent', 'glue ear serous otitis media effusion'),
    ('H66.0', 'Acute suppurative otitis media', 'ent', 'acute otitis media AOM ear infection'),
    ('H66.9', 'Otitis media, unspecified', 'ent', 'otitis media ear infection'),
    ('H72.0', 'Central perforation of tympanic membrane', 'ent', 'perforated eardrum tympanic membrane'),
    ('H81.1', 'Benign paroxysmal vertigo', 'ent', 'BPPV vertigo positional'),
    ('H81.3', 'Other peripheral vertigo', 'ent', 'vertigo labyrinthitis'),
    ('H83.3', 'Noise effects on inner ear', 'ent', 'noise induced hearing loss'),
    ('H90.3', 'Sensorineural hearing loss, bilateral', 'ent', 'sensorineural hearing loss deafness'),
    ('H91.9', 'Hearing loss, unspecified', 'ent', 'hearing loss deafness'),
    ('H92.0', 'Otalgia', 'ent', 'ear pain otalgia earache'),
    ('H93.1', 'Tinnitus', 'ent', 'tinnitus ringing in ears'),
    ('I05.9', 'Rheumatic mitral valve disease, unspecified', 'cardiovascular', 'rheumatic heart disease mitral RHD'),
    ('I10', 'Essential (primary) hypertension', 'cardiovascular', 'hypertension HTN high blood pressure BP'),
    ('I11.9', 'Hypertensive heart disease without (congestive) heart failure', 'cardiovascular', 'hypertensive heart disease LVH'),
    ('I12.9', 'Hypertensive renal disease without renal failure', 'cardiovascular', 'hypertensive nephropathy kidney'),
    ('I13.9', 'Hypertensive heart and renal disease, unspecified', 'cardiovascular', 'hypertensive heart and kidney disease'),
    ('I15.9', 'Secondary hypertension, unspecified', 'cardiovascular', 'secondary hypertension'),
    ('I20.0', 'Unstable angina', 'cardiovascular', 'unstable angina ACS chest pain'),
    ('I20.9', 'Angina pectoris, unspecified', 'cardiovascular', 'angina chest pain exertional'),
    ('I21.4', 'Acute subendocardial myocardial infarction', 'cardiovascular', 'NSTEMI heart attack myocardial infarction'),
    ('I21.9', 'Acute myocardial infarction, unspecified', 'cardiovascular', 'MI heart attack STEMI'),
    ('I25.1', 'Atherosclerotic heart disease', 'cardiovascular', 'coronary artery disease CAD IHD'),
    ('I25.9', 'Chronic ischaemic heart disease, unspecified', 'cardiovascular', 'ischaemic heart disease IHD'),
    ('I26.9', 'Pulmonary embolism without mention of acute cor pulmonale', 'cardiovascular', 'PE pulmonary embolism clot lung'),
    ('I34.0', 'Mitral (valve) insufficiency', 'cardiovascular', 'mitral regurgitation MR murmur'),
    ('I35.0', 'Aortic (valve) stenosis', 'cardiovascular', 'aortic stenosis AS murmur'),
    ('I42.0', 'Dilated cardiomyopathy', 'cardiovascular', 'dilated cardiomyopathy DCM'),
    ('I47.1', 'Supraventricular tachycardia', 'cardiovascular', 'SVT palpitations tachycardia'),
    ('I48.9', 'Atrial fibrillation and flutter, unspecified', 'cardiovascular', 'AF atrial fibrillation irregular pulse'),
    ('I49.9', 'Cardiac arrhythmia, unspecified', 'cardiovascular', 'arrhythmia palpitations irregular heartbeat'),
    ('I50.0', 'Congestive heart failure', 'cardiovascular', 'CCF congestive cardiac failure oedema'),
    ('I50.9', 'Heart failure, unspecified', 'cardiovascular', 'heart failure HF breathlessness'),
    ('I61.9', 'Intracerebral haemorrhage, unspecified', 'cardiovascular', 'haemorrhagic stroke intracerebral bleed'),
    ('I63.9', 'Cerebral infarction, unspecified', 'cardiovascular', 'ischaemic stroke CVA infarct'),
    ('I64', 'Stroke, not specified as haemorrhage or infarction', 'cardiovascular', 'stroke CVA'),
    ('I69.4', 'Sequelae of stroke, not specified as haemorrhage or infarction', 'cardiovascular', 'post stroke sequelae hemiparesis'),
    ('I70.2', 'Atherosclerosis of arteries of extremities', 'cardiovascular', 'peripheral arterial disease claudication'),
    ('I73.9', 'Peripheral vascular disease, unspecified', 'cardiovascular', 'PVD peripheral vascular'),
    ('I80.2', 'Phlebitis and thrombophlebitis of other deep vessels of lower extremities', 'cardiovascular', 'DVT deep vein thrombosis leg clot'),
    ('I83.9', 'Varicose veins of lower extremities without ulcer or inflammation', 'cardiovascular', 'varicose veins legs'),
    ('I87.2', 'Venous insufficiency (chronic) (peripheral)', 'cardiovascular', 'chronic venous insufficiency leg swelling'),
    ('I88.9', 'Nonspecific lymphadenitis, unspecified', 'haematology', 'lymphadenitis swollen glands'),
    ('I95.1', 'Orthostatic hypotension', 'cardiovascular', 'postural hypotension dizziness standing'),
    ('I99', 'Other and unspecified disorders of circulatory system', 'cardiovascular', 'circulatory disorder'),
    ('J00', 'Acute nasopharyngitis [common cold]', 'respiratory', 'common cold coryza runny nose'),
    ('J01.9', 'Acute sinusitis, unspecified', 'respiratory', 'sinusitis facial pain blocked nose'),
    ('J02.9', 'Acute pharyngitis, unspecified', 'respiratory', 'sore throat pharyngitis'),
    ('J03.9', 'Acute tonsillitis, unspecified', 'respiratory', 'tonsillitis sore throat'),
    ('J04.0', 'Acute laryngitis', 'respiratory', 'laryngitis hoarse voice'),
    ('J05.0', 'Acute obstructive laryngitis [croup]', 'paediatrics', 'croup barking cough stridor'),
    ('J06.9', 'Acute upper respiratory infection, unspecified', 'respiratory', 'URTI upper respiratory tract infection cold flu'),
    ('J09', 'Influenza due to identified zoonotic or pandemic influenza virus', 'respiratory', 'pandemic influenza avian flu'),
    ('J10.1', 'Influenza with other respiratory manifestations, seasonal influenza virus identified', 'respiratory', 'influenza flu confirmed'),
    ('J11.1', 'Influenza with other respiratory manifestations, virus not identified', 'respiratory', 'influenza flu clinical'),
    ('J12.9', 'Viral pneumonia, unspecified', 'respiratory', 'viral pneumonia'),
    ('J13', 'Pneumonia due to Streptococcus pneumoniae', 'respiratory', 'pneumococcal pneumonia'),
    ('J15.9', 'Bacterial pneumonia, unspecified', 'respiratory', 'bacterial pneumonia'),
    ('J18.0', 'Bronchopneumonia, unspecified', 'respiratory', 'bronchopneumonia'),
    ('J18.9', 'Pneumonia, unspecified organism', 'respiratory', 'pneumonia chest infection consolidation'),
    ('J20.9', 'Acute bronchitis, unspecified', 'respiratory', 'acute bronchitis chest infection cough'),
    ('J21.9', 'Acute bronchiolitis, unspecified', 'paediatrics', 'bronchiolitis RSV infant wheeze'),
    ('J22', 'Unspecified acute lower respiratory infection', 'respiratory', 'LRTI lower respiratory tract infection'),
    ('J30.1', 'Allergic rhinitis due to pollen', 'respiratory', 'hay fever seasonal allergic rhinitis'),
    ('J30.4', 'Allergic rhinitis, unspecified', 'respiratory', 'allergic rhinitis sneezing runny nose'),
    ('J31.0', 'Chronic rhinitis', 'respiratory', 'chronic rhinitis'),
    ('J32.9', 'Chronic sinusitis, unspecified', 'respiratory', 'chronic sinusitis'),
    ('J34.2', 'Deviated nasal septum', 'ent', 'deviated septum DNS blocked nose'),
    ('J35.0', 'Chronic tonsillitis', 'ent', 'chronic tonsillitis recurrent'),
    ('J35.1', 'Hypertrophy of tonsils', 'paediatrics', 'enlarged tonsils tonsillar hypertrophy'),
    ('J40', 'Bronchitis, not specified as acute or chronic', 'respiratory', 'bronchitis cough'),
    ('J42', 'Unspecified chronic bronchitis', 'respiratory', 'chronic bronchitis smoker cough'),
    ('J43.9', 'Emphysema, unspecified', 'respiratory', 'emphysema'),
    ('J44.0', 'Chronic obstructive pulmonary disease with acute lower respiratory infection', 'respiratory', 'COPD with infection'),
    ('J44.1', 'Chronic obstructive pulmonary disease with acute exacerbation', 'respiratory', 'COPD exacerbation AECOPD'),
    ('J44.9', 'Chronic obstructive pulmonary disease, unspecified', 'respiratory', 'COPD chronic obstructive pulmonary disease'),
    ('J45.0', 'Predominantly allergic asthma', 'respiratory', 'allergic asthma atopic'),
    ('J45.9', 'Asthma, unspecified', 'respiratory', 'asthma wheeze inhaler'),
    ('J46', 'Status asthmaticus', 'respiratory', 'acute severe asthma status asthmaticus'),
    ('J47', 'Bronchiectasis', 'respiratory', 'bronchiectasis chronic sputum'),
    ('J69.0', 'Pneumonitis due to food and vomit', 'respiratory', 'aspiration pneumonia'),
    ('J81', 'Pulmonary oedema', 'respiratory', 'pulmonary oedema APO'),
    ('J90', 'Pleural effusion, not elsewhere classified', 'respiratory', 'pleural effusion fluid lung'),
    ('J93.9', 'Pneumothorax, unspecified', 'respiratory', 'pneumothorax collapsed lung'),
    ('J96.0', 'Acute respiratory failure', 'respiratory', 'respiratory failure type 1 type 2 hypoxia'),
    ('J98.0', 'Diseases of bronchus, not elsewhere classified', 'respiratory', 'bronchial disease bronchospasm'),
    ('K02.9', 'Dental caries, unspecified', 'gastroenterology', 'dental caries tooth decay'),
    ('K05.3', 'Chronic periodontitis', 'gastroenterology', 'gum disease periodontitis'),
    ('K12.0', 'Recurrent oral aphthae', 'gastroenterology', 'mouth ulcer aphthous'),
    ('K21.0', 'Gastro-oesophageal reflux disease with oesophagitis', 'gastroenterology', 'GORD GERD reflux oesophagitis'),
    ('K21.9', 'Gastro-oesophageal reflux disease without oesophagitis', 'gastroenterology', 'GORD GERD reflux heartburn acidity'),
    ('K25.9', 'Gastric ulcer, unspecified as acute or chronic, without haemorrhage or perforation', 'gastroenterology', 'gastric ulcer peptic'),
    ('K26.9', 'Duodenal ulcer, unspecified as acute or chronic, without haemorrhage or perforation', 'gastroenterology', 'duodenal ulcer peptic DU'),
    ('K29.7', 'Gastritis, unspecified', 'gastroenterology', 'gastritis acidity stomach inflammation'),
    ('K29.9', 'Gastroduodenitis, unspecified', 'gastroenterology', 'gastroduodenitis'),
    ('K30', 'Functional dyspepsia', 'gastroenterology', 'dyspepsia indigestion bloating'),
    ('K35.8', 'Acute appendicitis, other and unspecified', 'gastroenterology', 'appendicitis RIF pain'),
    ('K40.9', 'Unilateral or unspecified inguinal hernia, without obstruction or gangrene', 'gastroenterology', 'inguinal hernia groin'),
    ('K42.9', 'Umbilical hernia without obstruction or gangrene', 'gastroenterology', 'umbilical hernia navel'),
    ('K44.9', 'Diaphragmatic hernia without obstruction or gangrene', 'gastroenterology', 'hiatus hernia diaphragmatic'),
    ('K52.9', 'Noninfective gastroenteritis and colitis, unspecified', 'gastroenterology', 'gastroenteritis noninfective colitis'),
    ('K57.3', 'Diverticular disease of large intestine without perforation or abscess', 'gastroenterology', 'diverticular disease diverticulosis'),
    ('K58.0', 'Irritable bowel syndrome with diarrhoea', 'gastroenterology', 'IBS diarrhoea predominant'),
    ('K58.9', 'Irritable bowel syndrome without diarrhoea', 'gastroenterology', 'IBS irritable bowel'),
    ('K59.0', 'Constipation', 'gastroenterology', 'constipation hard stools'),
    ('K59.1', 'Functional diarrhoea', 'gastroenterology', 'functional diarrhoea'),
    ('K60.2', 'Anal fissure, unspecified', 'gastroenterology', 'anal fissure painful defaecation'),
    ('K61.0', 'Anal abscess', 'gastroenterology', 'perianal abscess'),
    ('K64.9', 'Haemorrhoids, unspecified', 'gastroenterology', 'piles haemorrhoids bleeding per rectum'),
    ('K70.3', 'Alcoholic cirrhosis of liver', 'gastroenterology', 'alcoholic cirrhosis liver'),
    ('K71.9', 'Toxic liver disease, unspecified', 'gastroenterology', 'drug induced liver injury hepatotoxicity'),
    ('K73.9', 'Chronic hepatitis, unspecified', 'gastroenterology', 'chronic hepatitis'),
    ('K74.6', 'Other and unspecified cirrhosis of liver', 'gastroenterology', 'cirrhosis liver failure'),
    ('K76.0', 'Fatty (change of) liver, not elsewhere classified', 'gastroenterology', 'fatty liver NAFLD hepatic steatosis'),
    ('K80.2', 'Calculus of gallbladder without cholecystitis', 'gastroenterology', 'gallstones cholelithiasis'),
    ('K81.0', 'Acute cholecystitis', 'gastroenterology', 'cholecystitis gallbladder infection'),
    ('K85.9', 'Acute pancreatitis, unspecified', 'gastroenterology', 'acute pancreatitis'),
    ('K86.1', 'Other chronic pancreatitis', 'gastroenterology', 'chronic pancreatitis'),
    ('K90.0', 'Coeliac disease', 'gastroenterology', 'coeliac gluten enteropathy'),
    ('K92.2', 'Gastrointestinal haemorrhage, unspecified', 'gastroenterology', 'GI bleed melaena haematemesis'),
    ('L01.0', 'Impetigo', 'dermatology', 'impetigo school sores golden crust'),
    ('L02.9', 'Cutaneous abscess, furuncle and carbuncle, unspecified', 'dermatology', 'abscess boil furuncle'),
    ('L03.9', 'Cellulitis, unspecified', 'dermatology', 'cellulitis skin infection'),
    ('L04.9', 'Acute lymphadenitis, unspecified', 'dermatology', 'lymphadenitis tender node'),
    ('L08.9', 'Local infection of skin and subcutaneous tissue, unspecified', 'dermatology', 'skin infection'),
    ('L20.9', 'Atopic dermatitis, unspecified', 'dermatology', 'eczema atopic dermatitis itchy'),
    ('L21.9', 'Seborrhoeic dermatitis, unspecified', 'dermatology', 'seborrhoeic dermatitis dandruff'),
    ('L22', 'Diaper [napkin] dermatitis', 'paediatrics', 'nappy rash diaper dermatitis'),
    ('L23.9', 'Allergic contact dermatitis, unspecified cause', 'dermatology', 'allergic contact dermatitis'),
    ('L24.9', 'Irritant contact dermatitis, unspecified cause', 'dermatology', 'irritant contact dermatitis'),
    ('L27.0', 'Generalized skin eruption due to drugs and medicaments', 'dermatology', 'drug rash drug eruption'),
    ('L28.0', 'Lichen simplex chronicus', 'dermatology', 'lichen simplex chronic itch'),
    ('L29.9', 'Pruritus, unspecified', 'dermatology', 'itching pruritus'),
    ('L30.9', 'Dermatitis, unspecified', 'dermatology', 'dermatitis rash eczema'),
    ('L40.0', 'Psoriasis vulgaris', 'dermatology', 'plaque psoriasis'),
    ('L40.9', 'Psoriasis, unspecified', 'dermatology', 'psoriasis scaly plaques'),
    ('L42', 'Pityriasis rosea', 'dermatology', 'pityriasis rosea herald patch'),
    ('L43.9', 'Lichen planus, unspecified', 'dermatology', 'lichen planus'),
    ('L50.0', 'Allergic urticaria', 'dermatology', 'allergic urticaria hives'),
    ('L50.9', 'Urticaria, unspecified', 'dermatology', 'urticaria hives weals'),
    ('L51.9', 'Erythema multiforme, unspecified', 'dermatology', 'erythema multiforme target lesions'),
    ('L53.9', 'Erythematous condition, unspecified', 'dermatology', 'erythema redness'),
    ('L57.0', 'Actinic keratosis', 'dermatology', 'actinic keratosis solar keratosis'),
    ('L60.0', 'Ingrowing nail', 'dermatology', 'ingrown toenail'),
    ('L63.9', 'Alopecia areata, unspecified', 'dermatology', 'alopecia areata patchy hair loss'),
    ('L64.9', 'Androgenic alopecia, unspecified', 'dermatology', 'male pattern baldness androgenic alopecia'),
    ('L65.9', 'Nonscarring hair loss, unspecified', 'dermatology', 'hair fall telogen effluvium'),
    ('L70.0', 'Acne vulgaris', 'dermatology', 'acne pimples vulgaris'),
    ('L70.9', 'Acne, unspecified', 'dermatology', 'acne'),
    ('L71.9', 'Rosacea, unspecified', 'dermatology', 'rosacea facial flushing'),
    ('L72.0', 'Epidermal cyst', 'dermatology', 'sebaceous cyst epidermal'),
    ('L73.9', 'Follicular disorder, unspecified', 'dermatology', 'folliculitis'),
    ('L80', 'Vitiligo', 'dermatology', 'vitiligo white patches'),
    ('L81.4', 'Other melanin hyperpigmentation', 'dermatology', 'melasma hyperpigmentation dark patches'),
    ('L82', 'Seborrhoeic keratosis', 'dermatology', 'seborrhoeic keratosis'),
    ('L84', 'Corns and callosities', 'dermatology', 'corn callus'),
    ('L85.3', 'Xerosis cutis', 'dermatology', 'dry skin xerosis'),
    ('L89.9', 'Decubitus ulcer and pressure area, unspecified', 'dermatology', 'pressure sore bed sore decubitus'),
    ('L90.5', 'Scar conditions and fibrosis of skin', 'dermatology', 'scar fibrosis'),
    ('L91.0', 'Hypertrophic scar', 'dermatology', 'keloid hypertrophic scar'),
    ('L98.9', 'Disorder of skin and subcutaneous tissue, unspecified', 'dermatology', 'skin disorder'),
    ('M05.9', 'Seropositive rheumatoid arthritis, unspecified', 'musculoskeletal', 'rheumatoid arthritis RF positive'),
    ('M06.9', 'Rheumatoid arthritis, unspecified', 'musculoskeletal', 'rheumatoid arthritis RA'),
    ('M10.9', 'Gout, unspecified', 'musculoskeletal', 'gout uric acid podagra'),
    ('M13.9', 'Arthritis, unspecified', 'musculoskeletal', 'arthritis joint inflammation'),
    ('M15.0', 'Primary generalized (osteo)arthrosis', 'musculoskeletal', 'generalised osteoarthritis'),
    ('M16.9', 'Coxarthrosis, unspecified', 'musculoskeletal', 'hip osteoarthritis coxarthrosis'),
    ('M17.9', 'Gonarthrosis, unspecified', 'musculoskeletal', 'knee osteoarthritis gonarthrosis OA knee'),
    ('M19.9', 'Arthrosis, unspecified', 'musculoskeletal', 'osteoarthritis OA degenerative'),
    ('M20.1', 'Hallux valgus (acquired)', 'musculoskeletal', 'bunion hallux valgus'),
    ('M25.4', 'Effusion of joint', 'musculoskeletal', 'joint effusion swelling'),
    ('M25.5', 'Pain in joint', 'musculoskeletal', 'joint pain arthralgia'),
    ('M32.9', 'Systemic lupus erythematosus, unspecified', 'musculoskeletal', 'SLE lupus'),
    ('M35.0', 'Sicca syndrome [Sjogren]', 'musculoskeletal', 'sjogren dry eyes dry mouth'),
    ('M45', 'Ankylosing spondylitis', 'musculoskeletal', 'ankylosing spondylitis AS back stiffness'),
    ('M47.9', 'Spondylosis, unspecified', 'musculoskeletal', 'spondylosis degenerative spine'),
    ('M48.0', 'Spinal stenosis', 'musculoskeletal', 'spinal stenosis canal narrowing'),
    ('M50.2', 'Other cervical disc displacement', 'musculoskeletal', 'cervical disc prolapse neck'),
    ('M51.2', 'Other specified intervertebral disc displacement', 'musculoskeletal', 'lumbar disc prolapse PID slipped disc'),
    ('M53.1', 'Cervicobrachial syndrome', 'musculoskeletal', 'cervicobrachial neck arm pain'),
    ('M54.2', 'Cervicalgia', 'musculoskeletal', 'neck pain cervicalgia'),
    ('M54.3', 'Sciatica', 'musculoskeletal', 'sciatica leg pain radiculopathy'),
    ('M54.4', 'Lumbago with sciatica', 'musculoskeletal', 'back pain with sciatica'),
    ('M54.5', 'Low back pain', 'musculoskeletal', 'low back pain lumbago LBP'),
    ('M54.6', 'Pain in thoracic spine', 'musculoskeletal', 'thoracic back pain'),
    ('M54.9', 'Dorsalgia, unspecified', 'musculoskeletal', 'back pain dorsalgia'),
    ('M62.6', 'Muscle strain', 'musculoskeletal', 'muscle strain pull'),
    ('M65.3', 'Trigger finger', 'musculoskeletal', 'trigger finger stenosing tenosynovitis'),
    ('M65.9', 'Synovitis and tenosynovitis, unspecified', 'musculoskeletal', 'tenosynovitis synovitis'),
    ('M67.4', 'Ganglion', 'musculoskeletal', 'ganglion cyst wrist'),
    ('M72.2', 'Plantar fascial fibromatosis', 'musculoskeletal', 'plantar fasciitis heel pain'),
    ('M75.0', 'Adhesive capsulitis of shoulder', 'musculoskeletal', 'frozen shoulder adhesive capsulitis'),
    ('M75.1', 'Rotator cuff syndrome', 'musculoskeletal', 'rotator cuff shoulder impingement'),
    ('M76.6', 'Achilles tendinitis', 'musculoskeletal', 'achilles tendinitis heel'),
    ('M77.0', 'Medial epicondylitis', 'musculoskeletal', 'golfer elbow medial epicondylitis'),
    ('M77.1', 'Lateral epicondylitis', 'musculoskeletal', 'tennis elbow lateral epicondylitis'),
    ('M79.1', 'Myalgia', 'musculoskeletal', 'muscle pain myalgia body aches'),
    ('M79.2', 'Neuralgia and neuritis, unspecified', 'musculoskeletal', 'neuralgia nerve pain'),
    ('M79.7', 'Fibromyalgia', 'musculoskeletal', 'fibromyalgia widespread pain'),
    ('M81.9', 'Osteoporosis, unspecified', 'musculoskeletal', 'osteoporosis thin bones'),
    ('M86.9', 'Osteomyelitis, unspecified', 'musculoskeletal', 'osteomyelitis bone infection'),
    ('M89.9', 'Disorder of bone, unspecified', 'musculoskeletal', 'bone disorder'),
    ('N04.9', 'Nephrotic syndrome, unspecified', 'renal', 'nephrotic syndrome proteinuria oedema'),
    ('N10', 'Acute tubulo-interstitial nephritis', 'renal', 'acute pyelonephritis kidney infection'),
    ('N17.9', 'Acute renal failure, unspecified', 'renal', 'AKI acute kidney injury'),
    ('N18.3', 'Chronic kidney disease, stage 3', 'renal', 'CKD stage 3'),
    ('N18.5', 'Chronic kidney disease, stage 5', 'renal', 'CKD stage 5 ESRD dialysis'),
    ('N18.9', 'Chronic kidney disease, unspecified', 'renal', 'CKD chronic kidney disease CKDu'),
    ('N19', 'Unspecified kidney failure', 'renal', 'renal failure'),
    ('N20.0', 'Calculus of kidney', 'renal', 'kidney stone renal calculus'),
    ('N20.1', 'Calculus of ureter', 'renal', 'ureteric stone'),
    ('N23', 'Unspecified renal colic', 'renal', 'renal colic loin pain'),
    ('N30.0', 'Acute cystitis', 'renal', 'acute cystitis bladder infection'),
    ('N30.9', 'Cystitis, unspecified', 'renal', 'cystitis bladder'),
    ('N39.0', 'Urinary tract infection, site not specified', 'renal', 'UTI urine infection dysuria'),
    ('N39.3', 'Stress incontinence', 'renal', 'stress incontinence leaking urine'),
    ('N40', 'Hyperplasia of prostate', 'renal', 'BPH enlarged prostate prostatic hyperplasia'),
    ('N41.0', 'Acute prostatitis', 'renal', 'prostatitis'),
    ('N43.3', 'Hydrocele, unspecified', 'renal', 'hydrocele scrotal swelling'),
    ('N45.9', 'Orchitis, epididymitis and epididymo-orchitis without abscess', 'renal', 'epididymitis orchitis testicular pain'),
    ('N47', 'Redundant prepuce, phimosis and paraphimosis', 'renal', 'phimosis paraphimosis foreskin'),
    ('N48.1', 'Balanoposthitis', 'renal', 'balanitis balanoposthitis'),
    ('N52.9', 'Male erectile dysfunction, unspecified', 'renal', 'erectile dysfunction ED impotence'),
    ('N60.1', 'Diffuse cystic mastopathy', 'gynaecology', 'fibrocystic breast disease'),
    ('N61', 'Inflammatory disorders of breast', 'gynaecology', 'mastitis breast abscess'),
    ('N63', 'Unspecified lump in breast', 'gynaecology', 'breast lump'),
    ('N64.4', 'Mastodynia', 'gynaecology', 'breast pain mastalgia'),
    ('N70.9', 'Salpingitis and oophoritis, unspecified', 'gynaecology', 'salpingitis oophoritis'),
    ('N72', 'Inflammatory disease of cervix uteri', 'gynaecology', 'cervicitis'),
    ('N73.9', 'Female pelvic inflammatory disease, unspecified', 'gynaecology', 'PID pelvic inflammatory disease'),
    ('N75.0', 'Cyst of Bartholin gland', 'gynaecology', 'bartholin cyst'),
    ('N76.0', 'Acute vaginitis', 'gynaecology', 'vaginitis discharge'),
    ('N80.9', 'Endometriosis, unspecified', 'gynaecology', 'endometriosis pelvic pain'),
    ('N83.2', 'Other and unspecified ovarian cysts', 'gynaecology', 'ovarian cyst'),
    ('N84.0', 'Polyp of corpus uteri', 'gynaecology', 'endometrial polyp'),
    ('N87.9', 'Dysplasia of cervix uteri, unspecified', 'gynaecology', 'cervical dysplasia CIN abnormal pap'),
    ('N91.2', 'Amenorrhoea, unspecified', 'gynaecology', 'amenorrhoea missed periods'),
    ('N92.0', 'Excessive and frequent menstruation with regular cycle', 'gynaecology', 'menorrhagia heavy periods'),
    ('N92.6', 'Irregular menstruation, unspecified', 'gynaecology', 'irregular periods'),
    ('N93.9', 'Abnormal uterine and vaginal bleeding, unspecified', 'gynaecology', 'abnormal uterine bleeding AUB'),
    ('N94.6', 'Dysmenorrhoea, unspecified', 'gynaecology', 'period pain dysmenorrhoea cramps'),
    ('N95.1', 'Menopausal and female climacteric states', 'gynaecology', 'menopause hot flushes climacteric'),
    ('N97.9', 'Female infertility, unspecified', 'gynaecology', 'infertility subfertility'),
    ('O03.9', 'Complete or unspecified spontaneous abortion without complication', 'obstetrics', 'miscarriage spontaneous abortion'),
    ('O13', 'Gestational [pregnancy-induced] hypertension without significant proteinuria', 'obstetrics', 'pregnancy induced hypertension PIH'),
    ('O14.9', 'Pre-eclampsia, unspecified', 'obstetrics', 'pre-eclampsia PET proteinuria pregnancy'),
    ('O20.0', 'Threatened abortion', 'obstetrics', 'threatened miscarriage bleeding early pregnancy'),
    ('O21.0', 'Mild hyperemesis gravidarum', 'obstetrics', 'morning sickness hyperemesis'),
    ('O21.1', 'Hyperemesis gravidarum with metabolic disturbance', 'obstetrics', 'severe hyperemesis gravidarum'),
    ('O23.4', 'Unspecified infection of urinary tract in pregnancy', 'obstetrics', 'UTI in pregnancy'),
    ('O24.4', 'Diabetes mellitus arising in pregnancy', 'obstetrics', 'gestational diabetes GDM'),
    ('O26.9', 'Pregnancy-related condition, unspecified', 'obstetrics', 'pregnancy related condition'),
    ('O47.9', 'False labour, unspecified', 'obstetrics', 'false labour braxton hicks'),
    ('O80', 'Single spontaneous delivery', 'obstetrics', 'normal vaginal delivery NVD'),
    ('O91.2', 'Nonpurulent mastitis associated with childbirth', 'obstetrics', 'lactational mastitis breastfeeding'),
    ('O99.0', 'Anaemia complicating pregnancy, childbirth and the puerperium', 'obstetrics', 'anaemia in pregnancy'),
    ('P07.3', 'Other preterm infants', 'paediatrics', 'preterm infant prematurity'),
    ('P39.9', 'Infection specific to the perinatal period, unspecified', 'paediatrics', 'neonatal sepsis infection'),
    ('P59.9', 'Neonatal jaundice, unspecified', 'paediatrics', 'neonatal jaundice newborn bilirubin'),
    ('P92.9', 'Feeding problem of newborn, unspecified', 'paediatrics', 'newborn feeding problem poor feeding'),
    ('Q21.0', 'Ventricular septal defect', 'paediatrics', 'VSD hole in heart'),
    ('Q21.1', 'Atrial septal defect', 'paediatrics', 'ASD hole in heart'),
    ('Q25.0', 'Patent ductus arteriosus', 'paediatrics', 'PDA ductus arteriosus'),
    ('Q38.1', 'Ankyloglossia', 'paediatrics', 'tongue tie ankyloglossia'),
    ('Q53.9', 'Undescended testicle, unspecified', 'paediatrics', 'undescended testis cryptorchidism'),
    ('Q54.9', 'Hypospadias, unspecified', 'paediatrics', 'hypospadias'),
    ('Q65.9', 'Congenital deformity of hip, unspecified', 'paediatrics', 'developmental dysplasia hip DDH'),
    ('Q66.8', 'Other congenital deformities of feet', 'paediatrics', 'club foot talipes foot deformity'),
    ('Q82.5', 'Congenital non-neoplastic naevus', 'paediatrics', 'birthmark congenital naevus'),
    ('Q90.9', 'Down syndrome, unspecified', 'paediatrics', 'down syndrome trisomy 21'),
    ('R00.0', 'Tachycardia, unspecified', 'symptoms', 'tachycardia fast heart rate'),
    ('R00.1', 'Bradycardia, unspecified', 'symptoms', 'bradycardia slow heart rate'),
    ('R03.0', 'Elevated blood-pressure reading, without diagnosis of hypertension', 'symptoms', 'raised BP reading white coat'),
    ('R04.0', 'Epistaxis', 'symptoms', 'nose bleed epistaxis'),
    ('R05', 'Cough', 'symptoms', 'cough'),
    ('R06.0', 'Dyspnoea', 'symptoms', 'breathlessness shortness of breath SOB dyspnoea'),
    ('R06.2', 'Wheezing', 'symptoms', 'wheeze wheezing'),
    ('R07.0', 'Pain in throat', 'symptoms', 'sore throat throat pain'),
    ('R07.4', 'Chest pain, unspecified', 'symptoms', 'chest pain'),
    ('R09.8', 'Other specified symptoms and signs involving the circulatory and respiratory systems', 'symptoms', 'nasal congestion blocked nose chest signs'),
    ('R10.1', 'Pain localized to upper abdomen', 'symptoms', 'epigastric pain upper abdominal pain'),
    ('R10.3', 'Pain localized to other parts of lower abdomen', 'symptoms', 'lower abdominal pain pelvic pain'),
    ('R10.4', 'Other and unspecified abdominal pain', 'symptoms', 'abdominal pain stomach ache tummy pain'),
    ('R11', 'Nausea and vomiting', 'symptoms', 'nausea vomiting'),
    ('R14', 'Flatulence and related conditions', 'symptoms', 'bloating flatulence gas'),
    ('R17', 'Unspecified jaundice', 'symptoms', 'jaundice yellow eyes'),
    ('R18', 'Ascites', 'symptoms', 'ascites abdominal distension'),
    ('R19.7', 'Diarrhoea, unspecified', 'symptoms', 'diarrhoea loose stools'),
    ('R20.2', 'Paraesthesia of skin', 'symptoms', 'numbness tingling pins and needles'),
    ('R21', 'Rash and other nonspecific skin eruption', 'symptoms', 'rash skin eruption'),
    ('R22.9', 'Localized swelling, mass and lump, unspecified', 'symptoms', 'lump swelling mass'),
    ('R25.1', 'Tremor, unspecified', 'symptoms', 'tremor shaking'),
    ('R26.8', 'Other and unspecified abnormalities of gait and mobility', 'symptoms', 'gait abnormality unsteady walking'),
    ('R30.0', 'Dysuria', 'symptoms', 'dysuria burning urination'),
    ('R31', 'Unspecified haematuria', 'symptoms', 'haematuria blood in urine'),
    ('R32', 'Unspecified urinary incontinence', 'symptoms', 'urinary incontinence'),
    ('R33', 'Retention of urine', 'symptoms', 'urinary retention cannot pass urine'),
    ('R35', 'Polyuria', 'symptoms', 'polyuria frequency nocturia'),
    ('R40.0', 'Somnolence', 'symptoms', 'drowsiness somnolence sleepy'),
    ('R41.0', 'Disorientation, unspecified', 'symptoms', 'confusion disorientation'),
    ('R42', 'Dizziness and giddiness', 'symptoms', 'dizziness giddiness lightheaded vertigo'),
    ('R43.0', 'Anosmia', 'symptoms', 'loss of smell anosmia'),
    ('R45.0', 'Nervousness', 'symptoms', 'nervousness restlessness'),
    ('R47.1', 'Dysarthria and anarthria', 'symptoms', 'slurred speech dysarthria'),
    ('R50.9', 'Fever, unspecified', 'symptoms', 'fever pyrexia temperature una'),
    ('R51', 'Headache', 'symptoms', 'headache cephalgia'),
    ('R52.9', 'Pain, unspecified', 'symptoms', 'pain'),
    ('R53', 'Malaise and fatigue', 'symptoms', 'fatigue tiredness malaise weakness'),
    ('R55', 'Syncope and collapse', 'symptoms', 'syncope faint collapse blackout'),
    ('R56.0', 'Febrile convulsions', 'paediatrics', 'febrile convulsion febrile fit'),
    ('R56.8', 'Other and unspecified convulsions', 'symptoms', 'convulsion seizure fit'),
    ('R59.0', 'Localized enlarged lymph nodes', 'symptoms', 'localised lymphadenopathy swollen gland'),
    ('R59.1', 'Generalized enlarged lymph nodes', 'symptoms', 'generalised lymphadenopathy'),
    ('R60.0', 'Localized oedema', 'symptoms', 'localised oedema swelling'),
    ('R60.1', 'Generalized oedema', 'symptoms', 'generalised oedema swelling'),
    ('R61.9', 'Hyperhidrosis, unspecified', 'symptoms', 'excessive sweating hyperhidrosis'),
    ('R63.0', 'Anorexia', 'symptoms', 'loss of appetite anorexia'),
    ('R63.4', 'Abnormal weight loss', 'symptoms', 'weight loss'),
    ('R63.5', 'Abnormal weight gain', 'symptoms', 'weight gain'),
    ('R68.8', 'Other specified general symptoms and signs', 'symptoms', 'chills rigors general symptoms'),
    ('R73.9', 'Hyperglycaemia, unspecified', 'symptoms', 'high blood sugar hyperglycaemia prediabetes'),
    ('R80', 'Isolated proteinuria', 'symptoms', 'proteinuria protein in urine'),
    ('R87.6', 'Abnormal findings in specimens from female genital organs: cytological', 'symptoms', 'abnormal pap smear cytology'),
    ('R94.3', 'Abnormal results of cardiovascular function studies', 'symptoms', 'abnormal ECG'),
    ('S00.0', 'Superficial injury of scalp', 'injury', 'scalp abrasion head bruise'),
    ('S01.9', 'Open wound of head, part unspecified', 'injury', 'head laceration cut'),
    ('S05.0', 'Injury of conjunctiva and corneal abrasion without foreign body', 'injury', 'corneal abrasion eye injury'),
    ('S06.0', 'Concussion', 'injury', 'concussion head injury'),
    ('S13.4', 'Sprain and strain of cervical spine', 'injury', 'whiplash neck sprain'),
    ('S20.2', 'Contusion of thorax', 'injury', 'chest contusion rib bruise'),
    ('S33.5', 'Sprain and strain of lumbar spine', 'injury', 'lumbar sprain back strain'),
    ('S42.0', 'Fracture of clavicle', 'injury', 'clavicle fracture collarbone'),
    ('S52.5', 'Fracture of lower end of radius', 'injury', 'colles fracture distal radius wrist'),
    ('S60.0', 'Contusion of finger(s) without damage to nail', 'injury', 'finger contusion bruise'),
    ('S61.9', 'Open wound of wrist and hand, part unspecified', 'injury', 'hand laceration cut'),
    ('S62.6', 'Fracture of other finger', 'injury', 'finger fracture'),
    ('S63.5', 'Sprain and strain of wrist', 'injury', 'wrist sprain'),
    ('S72.0', 'Fracture of neck of femur', 'injury', 'hip fracture neck of femur NOF'),
    ('S82.6', 'Fracture of lateral malleolus', 'injury', 'ankle fracture lateral malleolus'),
    ('S83.5', 'Sprain and strain involving (anterior)(posterior) cruciate ligament of knee', 'injury', 'ACL sprain cruciate ligament knee'),
    ('S86.0', 'Injury of Achilles tendon', 'injury', 'achilles tendon rupture'),
    ('S93.4', 'Sprain and strain of ankle', 'injury', 'ankle sprain twisted ankle'),
    ('T14.9', 'Injury, unspecified', 'injury', 'injury unspecified trauma'),
    ('T15.0', 'Foreign body in cornea', 'injury', 'corneal foreign body eye'),
    ('T16', 'Foreign body in ear', 'injury', 'ear foreign body'),
    ('T18.1', 'Foreign body in oesophagus', 'injury', 'swallowed foreign body oesophagus'),
    ('T30.0', 'Burn of unspecified body region, unspecified degree', 'injury', 'burn scald'),
    ('T63.0', 'Toxic effect of snake venom', 'injury', 'snake bite envenomation cobra viper russell polonga naya'),
    ('T63.2', 'Toxic effect of venom of scorpion', 'injury', 'scorpion sting'),
    ('T63.3', 'Toxic effect of venom of spider', 'injury', 'spider bite'),
    ('T63.4', 'Toxic effect of venom of other arthropods', 'injury', 'bee sting wasp sting hornet insect'),
    ('T67.0', 'Heatstroke and sunstroke', 'injury', 'heat stroke sunstroke'),
    ('T78.0', 'Anaphylactic shock due to adverse food reaction', 'injury', 'food anaphylaxis'),
    ('T78.1', 'Other adverse food reactions, not elsewhere classified', 'injury', 'food allergy reaction'),
    ('T78.2', 'Anaphylactic shock, unspecified', 'injury', 'anaphylaxis anaphylactic shock'),
    ('T78.3', 'Angioneurotic oedema', 'injury', 'angioedema swelling lips'),
    ('T78.4', 'Allergy, unspecified', 'injury', 'allergy allergic reaction'),
    ('T88.7', 'Unspecified adverse effect of drug or medicament', 'injury', 'drug reaction adverse effect side effect'),
    ('W54', 'Bitten or struck by dog', 'injury', 'dog bite'),
    ('W57', 'Bitten or stung by nonvenomous insect and other nonvenomous arthropods', 'injury', 'insect bite'),
    ('X20', 'Contact with venomous snakes and lizards', 'injury', 'snake bite external cause'),
    ('Z00.0', 'General adult medical examination', 'preventive', 'health check medical examination'),
    ('Z00.1', 'Routine child health examination', 'paediatrics', 'child health check well baby'),
    ('Z01.4', 'Gynaecological examination (general)(routine)', 'preventive', 'gynaecological check pap smear'),
    ('Z03.9', 'Observation for suspected disease or condition, unspecified', 'preventive', 'observation suspected condition'),
    ('Z13.1', 'Special screening examination for diabetes mellitus', 'preventive', 'diabetes screening FBS'),
    ('Z20.9', 'Contact with and exposure to unspecified communicable disease', 'preventive', 'contact exposure infectious'),
    ('Z21', 'Asymptomatic human immunodeficiency virus [HIV] infection status', 'preventive', 'HIV positive asymptomatic'),
    ('Z23', 'Need for immunization against single bacterial diseases', 'preventive', 'vaccination immunisation'),
    ('Z27.9', 'Need for immunization against unspecified combinations of infectious diseases', 'preventive', 'vaccination combined immunisation'),
    ('Z30.0', 'General counselling and advice on contraception', 'preventive', 'contraception counselling family planning'),
    ('Z30.9', 'Contraceptive management, unspecified', 'preventive', 'contraception management'),
    ('Z32.1', 'Pregnant state, confirmed', 'obstetrics', 'confirmed pregnancy'),
    ('Z33', 'Pregnant state, incidental', 'obstetrics', 'incidental pregnancy'),
    ('Z34.9', 'Supervision of normal pregnancy, unspecified', 'obstetrics', 'antenatal care normal pregnancy ANC'),
    ('Z35.9', 'Supervision of high-risk pregnancy, unspecified', 'obstetrics', 'high risk pregnancy antenatal'),
    ('Z39.1', 'Care and examination of lactating mother', 'obstetrics', 'postnatal lactation breastfeeding'),
    ('Z71.3', 'Dietary counselling and surveillance', 'preventive', 'diet advice dietary counselling'),
    ('Z71.6', 'Tobacco abuse counselling', 'preventive', 'smoking cessation counselling'),
    ('Z72.0', 'Tobacco use', 'preventive', 'smoking tobacco use'),
    ('Z72.1', 'Alcohol use', 'preventive', 'alcohol use drinking'),
    ('Z76.0', 'Issue of repeat prescription', 'preventive', 'repeat prescription refill'),
    ('Z79.4', 'Long-term (current) use of insulin', 'preventive', 'insulin long term use'),
    ('Z88.0', 'Personal history of allergy to penicillin', 'preventive', 'penicillin allergy history'),
    ('Z91.1', 'Personal history of noncompliance with medical treatment and regimen', 'preventive', 'noncompliance defaulter')
ON CONFLICT (code) DO NOTHING;
