-- Reverses 000003 exactly: remove only the rows this migration inserted, by
-- the same (name, strength, form) keys, rather than truncating the table --
-- an operator may have added their own formulary entries by then.
DELETE FROM drugs WHERE (name, strength, form) IN (
    ('Panadol', '500mg', 'tablet'),
    ('Paracetamol', '500mg', 'tablet'),
    ('Paracetamol Syrup', '120mg/5ml', 'syrup'),
    ('Amoxil', '500mg', 'capsule'),
    ('Amoxicillin', '250mg/5ml', 'syrup'),
    ('Augmentin', '625mg', 'tablet'),
    ('Flagyl', '400mg', 'tablet'),
    ('Ciprofloxacin', '500mg', 'tablet'),
    ('Azithromycin', '500mg', 'tablet'),
    ('Glucophage', '500mg', 'tablet'),
    ('Metformin', '500mg', 'tablet'),
    ('Diamicron MR', '60mg', 'tablet'),
    ('Amaryl', '2mg', 'tablet'),
    ('Lantus', '100units/ml', 'injection'),
    ('Amlodipine', '5mg', 'tablet'),
    ('Norvasc', '5mg', 'tablet'),
    ('Losartan', '50mg', 'tablet'),
    ('Cozaar', '50mg', 'tablet'),
    ('Enalapril', '10mg', 'tablet'),
    ('Concor', '5mg', 'tablet'),
    ('Atorvastatin', '20mg', 'tablet'),
    ('Lipitor', '20mg', 'tablet'),
    ('Omeprazole', '20mg', 'capsule'),
    ('Losec', '20mg', 'capsule'),
    ('Zantac', '150mg', 'tablet'),
    ('Domperidone', '10mg', 'tablet'),
    ('Cetirizine', '10mg', 'tablet'),
    ('Piriton', '4mg', 'tablet'),
    ('Ventolin', '100mcg/dose', 'inhaler'),
    ('Salbutamol', '2mg/5ml', 'syrup'),
    ('Seretide', '25/125mcg', 'inhaler'),
    ('Prednisolone', '5mg', 'tablet'),
    ('Betnovate', '0.1%', 'cream'),
    ('Diclofenac', '50mg', 'tablet'),
    ('Voltaren', '50mg', 'tablet'),
    ('Ibuprofen', '400mg', 'tablet'),
    ('Tramadol', '50mg', 'capsule'),
    ('Diazepam', '5mg', 'tablet'),
    ('Alprazolam', '0.25mg', 'tablet'),
    ('ORS', 'WHO formula', 'sachet'),
    ('Folic Acid', '5mg', 'tablet'),
    ('Iberet Folic', '105mg/0.35mg', 'tablet'),
    ('Calcium Carbonate', '500mg', 'tablet'),
    ('Metoclopramide', '10mg', 'tablet'),
    ('Loratadine', '10mg', 'tablet'),
    ('Cefuroxime', '500mg', 'tablet'),
    ('Doxycycline', '100mg', 'capsule'),
    ('Aspirin', '75mg', 'tablet'),
    ('Clopidogrel', '75mg', 'tablet')
);
