// The internal gRPC surface doctor-service exposes to the rest of the
// platform.
//
// Other services never join across the database boundary to read a doctor's
// fee, specialty or verification state (see DECISIONS.md ADR-004); they call
// GetDoctor/GetDoctorsBatch instead. Payment-service uses fee_lkr and
// specialty to compute commission; scheduling-service uses verification_status
// to decide whether a doctor is eligible for slot generation;
// consultation-service uses display_name for room metadata. This file is the
// contract for those calls, versioned so a breaking change ships as doctor.v2
// alongside v1 rather than as a silent behaviour change.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/doctor/v1/doctor.proto

package doctorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DoctorService_GetDoctor_FullMethodName       = "/telemed.doctor.v1.DoctorService/GetDoctor"
	DoctorService_GetDoctorsBatch_FullMethodName = "/telemed.doctor.v1.DoctorService/GetDoctorsBatch"
)

// DoctorServiceClient is the client API for DoctorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DoctorServiceClient interface {
	// GetDoctor returns one doctor by id. Callers must treat NOT_FOUND as a
	// valid outcome (e.g. a stale foreign reference in another service's
	// table) and must not treat it as a system error.
	GetDoctor(ctx context.Context, in *GetDoctorRequest, opts ...grpc.CallOption) (*GetDoctorResponse, error)
	// GetDoctorsBatch resolves many ids in one round trip, e.g. rendering a
	// patient's appointment list with doctor names attached. Unknown ids are
	// silently omitted from the response rather than failing the whole call.
	GetDoctorsBatch(ctx context.Context, in *GetDoctorsBatchRequest, opts ...grpc.CallOption) (*GetDoctorsBatchResponse, error)
}

type doctorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDoctorServiceClient(cc grpc.ClientConnInterface) DoctorServiceClient {
	return &doctorServiceClient{cc}
}

func (c *doctorServiceClient) GetDoctor(ctx context.Context, in *GetDoctorRequest, opts ...grpc.CallOption) (*GetDoctorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorResponse)
	err := c.cc.Invoke(ctx, DoctorService_GetDoctor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *doctorServiceClient) GetDoctorsBatch(ctx context.Context, in *GetDoctorsBatchRequest, opts ...grpc.CallOption) (*GetDoctorsBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDoctorsBatchResponse)
	err := c.cc.Invoke(ctx, DoctorService_GetDoctorsBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoctorServiceServer is the server API for DoctorService service.
// All implementations must embed UnimplementedDoctorServiceServer
// for forward compatibility.
type DoctorServiceServer interface {
	// GetDoctor returns one doctor by id. Callers must treat NOT_FOUND as a
	// valid outcome (e.g. a stale foreign reference in another service's
	// table) and must not treat it as a system error.
	GetDoctor(context.Context, *GetDoctorRequest) (*GetDoctorResponse, error)
	// GetDoctorsBatch resolves many ids in one round trip, e.g. rendering a
	// patient's appointment list with doctor names attached. Unknown ids are
	// silently omitted from the response rather than failing the whole call.
	GetDoctorsBatch(context.Context, *GetDoctorsBatchRequest) (*GetDoctorsBatchResponse, error)
	mustEmbedUnimplementedDoctorServiceServer()
}

// UnimplementedDoctorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDoctorServiceServer struct{}

func (UnimplementedDoctorServiceServer) GetDoctor(context.Context, *GetDoctorRequest) (*GetDoctorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoctor not implemented")
}
func (UnimplementedDoctorServiceServer) GetDoctorsBatch(context.Context, *GetDoctorsBatchRequest) (*GetDoctorsBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoctorsBatch not implemented")
}
func (UnimplementedDoctorServiceServer) mustEmbedUnimplementedDoctorServiceServer() {}
func (UnimplementedDoctorServiceServer) testEmbeddedByValue()                       {}

// UnsafeDoctorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DoctorServiceServer will
// result in compilation errors.
type UnsafeDoctorServiceServer interface {
	mustEmbedUnimplementedDoctorServiceServer()
}

func RegisterDoctorServiceServer(s grpc.ServiceRegistrar, srv DoctorServiceServer) {
	// If the following call panics, it indicates UnimplementedDoctorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DoctorService_ServiceDesc, srv)
}

func _DoctorService_GetDoctor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetDoctor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetDoctor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetDoctor(ctx, req.(*GetDoctorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DoctorService_GetDoctorsBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDoctorsBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoctorServiceServer).GetDoctorsBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DoctorService_GetDoctorsBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoctorServiceServer).GetDoctorsBatch(ctx, req.(*GetDoctorsBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DoctorService_ServiceDesc is the grpc.ServiceDesc for DoctorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DoctorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemed.doctor.v1.DoctorService",
	HandlerType: (*DoctorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDoctor",
			Handler:    _DoctorService_GetDoctor_Handler,
		},
		{
			MethodName: "GetDoctorsBatch",
			Handler:    _DoctorService_GetDoctorsBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/doctor/v1/doctor.proto",
}
