// The internal gRPC surface doctor-service exposes to the rest of the
// platform.
//
// Other services never join across the database boundary to read a doctor's
// fee, specialty or verification state (see DECISIONS.md ADR-004); they call
// GetDoctor/GetDoctorsBatch instead. Payment-service uses fee_lkr and
// specialty to compute commission; scheduling-service uses verification_status
// to decide whether a doctor is eligible for slot generation;
// consultation-service uses display_name for room metadata. This file is the
// contract for those calls, versioned so a breaking change ships as doctor.v2
// alongside v1 rather than as a silent behaviour change.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/doctor/v1/doctor.proto

package doctorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Doctor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SlmcNumber         string                 `protobuf:"bytes,3,opt,name=slmc_number,json=slmcNumber,proto3" json:"slmc_number,omitempty"`
	Specialty          string                 `protobuf:"bytes,4,opt,name=specialty,proto3" json:"specialty,omitempty"`
	DisplayName        string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	FeeLkr             int64                  `protobuf:"varint,6,opt,name=fee_lkr,json=feeLkr,proto3" json:"fee_lkr,omitempty"` // cents
	Languages          []string               `protobuf:"bytes,7,rep,name=languages,proto3" json:"languages,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,8,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	Rating             float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount        int32                  `protobuf:"varint,10,opt,name=review_count,json=reviewCount,proto3" json:"review_count,omitempty"`
	AcceptsNewPatients bool                   `protobuf:"varint,11,opt,name=accepts_new_patients,json=acceptsNewPatients,proto3" json:"accepts_new_patients,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_proto_doctor_v1_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *Doctor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doctor) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Doctor) GetSlmcNumber() string {
	if x != nil {
		return x.SlmcNumber
	}
	return ""
}

func (x *Doctor) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Doctor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Doctor) GetFeeLkr() int64 {
	if x != nil {
		return x.FeeLkr
	}
	return 0
}

func (x *Doctor) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Doctor) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *Doctor) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Doctor) GetReviewCount() int32 {
	if x != nil {
		return x.ReviewCount
	}
	return 0
}

func (x *Doctor) GetAcceptsNewPatients() bool {
	if x != nil {
		return x.AcceptsNewPatients
	}
	return false
}

func (x *Doctor) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorId      string                 `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_v1_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDoctorRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type GetDoctorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctor        *Doctor                `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorResponse) Reset() {
	*x = GetDoctorResponse{}
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorResponse) ProtoMessage() {}

func (x *GetDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_v1_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *GetDoctorResponse) GetDoctor() *Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

type GetDoctorsBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DoctorIds     []string               `protobuf:"bytes,1,rep,name=doctor_ids,json=doctorIds,proto3" json:"doctor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorsBatchRequest) Reset() {
	*x = GetDoctorsBatchRequest{}
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorsBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsBatchRequest) ProtoMessage() {}

func (x *GetDoctorsBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsBatchRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorsBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_v1_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *GetDoctorsBatchRequest) GetDoctorIds() []string {
	if x != nil {
		return x.DoctorIds
	}
	return nil
}

type GetDoctorsBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*Doctor              `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorsBatchResponse) Reset() {
	*x = GetDoctorsBatchResponse{}
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsBatchResponse) ProtoMessage() {}

func (x *GetDoctorsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_v1_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsBatchResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorsBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_v1_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *GetDoctorsBatchResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

var File_proto_doctor_v1_doctor_proto protoreflect.FileDescriptor

const file_proto_doctor_v1_doctor_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/doctor/v1/doctor.proto\x12\x11telemed.doctor.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x03\n" +
	"\x06Doctor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vslmc_number\x18\x03 \x01(\tR\n" +
	"slmcNumber\x12\x1c\n" +
	"\tspecialty\x18\x04 \x01(\tR\tspecialty\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x17\n" +
	"\afee_lkr\x18\x06 \x01(\x03R\x06feeLkr\x12\x1c\n" +
	"\tlanguages\x18\a \x03(\tR\tlanguages\x12/\n" +
	"\x13verification_status\x18\b \x01(\tR\x12verificationStatus\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12!\n" +
	"\freview_count\x18\n" +
	" \x01(\x05R\vreviewCount\x120\n" +
	"\x14accepts_new_patients\x18\v \x01(\bR\x12acceptsNewPatients\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\x10GetDoctorRequest\x12\x1b\n" +
	"\tdoctor_id\x18\x01 \x01(\tR\bdoctorId\"F\n" +
	"\x11GetDoctorResponse\x121\n" +
	"\x06doctor\x18\x01 \x01(\v2\x19.telemed.doctor.v1.DoctorR\x06doctor\"7\n" +
	"\x16GetDoctorsBatchRequest\x12\x1d\n" +
	"\n" +
	"doctor_ids\x18\x01 \x03(\tR\tdoctorIds\"N\n" +
	"\x17GetDoctorsBatchResponse\x123\n" +
	"\adoctors\x18\x01 \x03(\v2\x19.telemed.doctor.v1.DoctorR\adoctors2\xd1\x01\n" +
	"\rDoctorService\x12V\n" +
	"\tGetDoctor\x12#.telemed.doctor.v1.GetDoctorRequest\x1a$.telemed.doctor.v1.GetDoctorResponse\x12h\n" +
	"\x0fGetDoctorsBatch\x12).telemed.doctor.v1.GetDoctorsBatchRequest\x1a*.telemed.doctor.v1.GetDoctorsBatchResponseB(Z&telemed/internal/pb/doctor/v1;doctorv1b\x06proto3"

var (
	file_proto_doctor_v1_doctor_proto_rawDescOnce sync.Once
	file_proto_doctor_v1_doctor_proto_rawDescData []byte
)

func file_proto_doctor_v1_doctor_proto_rawDescGZIP() []byte {
	file_proto_doctor_v1_doctor_proto_rawDescOnce.Do(func() {
		file_proto_doctor_v1_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doctor_v1_doctor_proto_rawDesc), len(file_proto_doctor_v1_doctor_proto_rawDesc)))
	})
	return file_proto_doctor_v1_doctor_proto_rawDescData
}

var file_proto_doctor_v1_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_doctor_v1_doctor_proto_goTypes = []any{
	(*Doctor)(nil),                  // 0: telemed.doctor.v1.Doctor
	(*GetDoctorRequest)(nil),        // 1: telemed.doctor.v1.GetDoctorRequest
	(*GetDoctorResponse)(nil),       // 2: telemed.doctor.v1.GetDoctorResponse
	(*GetDoctorsBatchRequest)(nil),  // 3: telemed.doctor.v1.GetDoctorsBatchRequest
	(*GetDoctorsBatchResponse)(nil), // 4: telemed.doctor.v1.GetDoctorsBatchResponse
	(*timestamppb.Timestamp)(nil),   // 5: google.protobuf.Timestamp
}
var file_proto_doctor_v1_doctor_proto_depIdxs = []int32{
	5, // 0: telemed.doctor.v1.Doctor.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: telemed.doctor.v1.GetDoctorResponse.doctor:type_name -> telemed.doctor.v1.Doctor
	0, // 2: telemed.doctor.v1.GetDoctorsBatchResponse.doctors:type_name -> telemed.doctor.v1.Doctor
	1, // 3: telemed.doctor.v1.DoctorService.GetDoctor:input_type -> telemed.doctor.v1.GetDoctorRequest
	3, // 4: telemed.doctor.v1.DoctorService.GetDoctorsBatch:input_type -> telemed.doctor.v1.GetDoctorsBatchRequest
	2, // 5: telemed.doctor.v1.DoctorService.GetDoctor:output_type -> telemed.doctor.v1.GetDoctorResponse
	4, // 6: telemed.doctor.v1.DoctorService.GetDoctorsBatch:output_type -> telemed.doctor.v1.GetDoctorsBatchResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_doctor_v1_doctor_proto_init() }
func file_proto_doctor_v1_doctor_proto_init() {
	if File_proto_doctor_v1_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doctor_v1_doctor_proto_rawDesc), len(file_proto_doctor_v1_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doctor_v1_doctor_proto_goTypes,
		DependencyIndexes: file_proto_doctor_v1_doctor_proto_depIdxs,
		MessageInfos:      file_proto_doctor_v1_doctor_proto_msgTypes,
	}.Build()
	File_proto_doctor_v1_doctor_proto = out.File
	file_proto_doctor_v1_doctor_proto_goTypes = nil
	file_proto_doctor_v1_doctor_proto_depIdxs = nil
}
