// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: scheduling/v1/scheduling.proto

// The internal, service-to-service scheduling API.
//
// It exists for the calls that sit on a user-facing latency budget and must not
// pay for JSON and HTTP/1.1: payment-service confirming a booking, and
// consultation-service resolving an appointment five minutes before a video
// call. Anything a patient's phone talks to goes over REST.

package schedulingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppointmentStatus int32

const (
	AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED     AppointmentStatus = 0
	AppointmentStatus_APPOINTMENT_STATUS_PENDING_PAYMENT AppointmentStatus = 1
	AppointmentStatus_APPOINTMENT_STATUS_CONFIRMED       AppointmentStatus = 2
	AppointmentStatus_APPOINTMENT_STATUS_CANCELLED       AppointmentStatus = 3
	AppointmentStatus_APPOINTMENT_STATUS_COMPLETED       AppointmentStatus = 4
	AppointmentStatus_APPOINTMENT_STATUS_NO_SHOW         AppointmentStatus = 5
)

// Enum value maps for AppointmentStatus.
var (
	AppointmentStatus_name = map[int32]string{
		0: "APPOINTMENT_STATUS_UNSPECIFIED",
		1: "APPOINTMENT_STATUS_PENDING_PAYMENT",
		2: "APPOINTMENT_STATUS_CONFIRMED",
		3: "APPOINTMENT_STATUS_CANCELLED",
		4: "APPOINTMENT_STATUS_COMPLETED",
		5: "APPOINTMENT_STATUS_NO_SHOW",
	}
	AppointmentStatus_value = map[string]int32{
		"APPOINTMENT_STATUS_UNSPECIFIED":     0,
		"APPOINTMENT_STATUS_PENDING_PAYMENT": 1,
		"APPOINTMENT_STATUS_CONFIRMED":       2,
		"APPOINTMENT_STATUS_CANCELLED":       3,
		"APPOINTMENT_STATUS_COMPLETED":       4,
		"APPOINTMENT_STATUS_NO_SHOW":         5,
	}
)

func (x AppointmentStatus) Enum() *AppointmentStatus {
	p := new(AppointmentStatus)
	*p = x
	return p
}

func (x AppointmentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppointmentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduling_v1_scheduling_proto_enumTypes[0].Descriptor()
}

func (AppointmentStatus) Type() protoreflect.EnumType {
	return &file_scheduling_v1_scheduling_proto_enumTypes[0]
}

func (x AppointmentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppointmentStatus.Descriptor instead.
func (AppointmentStatus) EnumDescriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{0}
}

type RefundPolicy int32

const (
	RefundPolicy_REFUND_POLICY_UNSPECIFIED RefundPolicy = 0
	RefundPolicy_REFUND_POLICY_FULL        RefundPolicy = 1
	RefundPolicy_REFUND_POLICY_PARTIAL     RefundPolicy = 2
	RefundPolicy_REFUND_POLICY_NONE        RefundPolicy = 3
)

// Enum value maps for RefundPolicy.
var (
	RefundPolicy_name = map[int32]string{
		0: "REFUND_POLICY_UNSPECIFIED",
		1: "REFUND_POLICY_FULL",
		2: "REFUND_POLICY_PARTIAL",
		3: "REFUND_POLICY_NONE",
	}
	RefundPolicy_value = map[string]int32{
		"REFUND_POLICY_UNSPECIFIED": 0,
		"REFUND_POLICY_FULL":        1,
		"REFUND_POLICY_PARTIAL":     2,
		"REFUND_POLICY_NONE":        3,
	}
)

func (x RefundPolicy) Enum() *RefundPolicy {
	p := new(RefundPolicy)
	*p = x
	return p
}

func (x RefundPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduling_v1_scheduling_proto_enumTypes[1].Descriptor()
}

func (RefundPolicy) Type() protoreflect.EnumType {
	return &file_scheduling_v1_scheduling_proto_enumTypes[1]
}

func (x RefundPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundPolicy.Descriptor instead.
func (RefundPolicy) EnumDescriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{1}
}

type Appointment struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId  string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	SlotId    string                 `protobuf:"bytes,4,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	StartAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Status    AppointmentStatus      `protobuf:"varint,7,opt,name=status,proto3,enum=scheduling.v1.AppointmentStatus" json:"status,omitempty"`
	// True when the patient's no-show history put them over the policy threshold
	// at booking time.
	PrepaymentRequired bool                   `protobuf:"varint,8,opt,name=prepayment_required,json=prepaymentRequired,proto3" json:"prepayment_required,omitempty"`
	RefundPolicy       RefundPolicy           `protobuf:"varint,9,opt,name=refund_policy,json=refundPolicy,proto3,enum=scheduling.v1.RefundPolicy" json:"refund_policy,omitempty"`
	Version            int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Deliberately absent: intake. It is PHI, and no caller of this API needs it.
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Appointment.ProtoReflect.Descriptor instead.
func (*Appointment) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{0}
}

func (x *Appointment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Appointment) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *Appointment) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *Appointment) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Appointment) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Appointment) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Appointment) GetStatus() AppointmentStatus {
	if x != nil {
		return x.Status
	}
	return AppointmentStatus_APPOINTMENT_STATUS_UNSPECIFIED
}

func (x *Appointment) GetPrepaymentRequired() bool {
	if x != nil {
		return x.PrepaymentRequired
	}
	return false
}

func (x *Appointment) GetRefundPolicy() RefundPolicy {
	if x != nil {
		return x.RefundPolicy
	}
	return RefundPolicy_REFUND_POLICY_UNSPECIFIED
}

func (x *Appointment) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Appointment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type BookSlotRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SlotId    string                 `protobuf:"bytes,1,opt,name=slot_id,json=slotId,proto3" json:"slot_id,omitempty"`
	PatientId string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	// Optional. When set it must match the slot's doctor, otherwise the call
	// fails NOT_FOUND rather than booking the wrong clinician.
	DoctorId       string `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	FamilyMemberId string `protobuf:"bytes,4,opt,name=family_member_id,json=familyMemberId,proto3" json:"family_member_id,omitempty"`
	// Opaque JSON. Kept out of logs and out of every event payload.
	IntakeJson    string `protobuf:"bytes,5,opt,name=intake_json,json=intakeJson,proto3" json:"intake_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSlotRequest) Reset() {
	*x = BookSlotRequest{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSlotRequest) ProtoMessage() {}

func (x *BookSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSlotRequest.ProtoReflect.Descriptor instead.
func (*BookSlotRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{1}
}

func (x *BookSlotRequest) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *BookSlotRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *BookSlotRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *BookSlotRequest) GetFamilyMemberId() string {
	if x != nil {
		return x.FamilyMemberId
	}
	return ""
}

func (x *BookSlotRequest) GetIntakeJson() string {
	if x != nil {
		return x.IntakeJson
	}
	return ""
}

type BookSlotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookSlotResponse) Reset() {
	*x = BookSlotResponse{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSlotResponse) ProtoMessage() {}

func (x *BookSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSlotResponse.ProtoReflect.Descriptor instead.
func (*BookSlotResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{2}
}

func (x *BookSlotResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

type CancelAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// "patient", "doctor" or "admin".
	ActorRole string `protobuf:"bytes,3,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	Reason    string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// Administrators only: cancel even though the slot has already started.
	Force         bool `protobuf:"varint,5,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentRequest) Reset() {
	*x = CancelAppointmentRequest{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentRequest) ProtoMessage() {}

func (x *CancelAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CancelAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{3}
}

func (x *CancelAppointmentRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *CancelAppointmentRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *CancelAppointmentRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

func (x *CancelAppointmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelAppointmentRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type CancelAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	RefundPolicy  RefundPolicy           `protobuf:"varint,2,opt,name=refund_policy,json=refundPolicy,proto3,enum=scheduling.v1.RefundPolicy" json:"refund_policy,omitempty"`
	RefundPercent int32                  `protobuf:"varint,3,opt,name=refund_percent,json=refundPercent,proto3" json:"refund_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAppointmentResponse) Reset() {
	*x = CancelAppointmentResponse{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAppointmentResponse) ProtoMessage() {}

func (x *CancelAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAppointmentResponse.ProtoReflect.Descriptor instead.
func (*CancelAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{4}
}

func (x *CancelAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

func (x *CancelAppointmentResponse) GetRefundPolicy() RefundPolicy {
	if x != nil {
		return x.RefundPolicy
	}
	return RefundPolicy_REFUND_POLICY_UNSPECIFIED
}

func (x *CancelAppointmentResponse) GetRefundPercent() int32 {
	if x != nil {
		return x.RefundPercent
	}
	return 0
}

type GetAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppointmentId string                 `protobuf:"bytes,1,opt,name=appointment_id,json=appointmentId,proto3" json:"appointment_id,omitempty"`
	// Optional ownership check. Leave both empty for a trusted internal read;
	// the mesh authenticates the caller, so this is defence in depth.
	ActorId       string `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	ActorRole     string `protobuf:"bytes,3,opt,name=actor_role,json=actorRole,proto3" json:"actor_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentRequest.ProtoReflect.Descriptor instead.
func (*GetAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppointmentRequest) GetAppointmentId() string {
	if x != nil {
		return x.AppointmentId
	}
	return ""
}

func (x *GetAppointmentRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *GetAppointmentRequest) GetActorRole() string {
	if x != nil {
		return x.ActorRole
	}
	return ""
}

type GetAppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appointment   *Appointment           `protobuf:"bytes,1,opt,name=appointment,proto3" json:"appointment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppointmentResponse) Reset() {
	*x = GetAppointmentResponse{}
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentResponse) ProtoMessage() {}

func (x *GetAppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduling_v1_scheduling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppointmentResponse.ProtoReflect.Descriptor instead.
func (*GetAppointmentResponse) Descriptor() ([]byte, []int) {
	return file_scheduling_v1_scheduling_proto_rawDescGZIP(), []int{6}
}

func (x *GetAppointmentResponse) GetAppointment() *Appointment {
	if x != nil {
		return x.Appointment
	}
	return nil
}

var File_scheduling_v1_scheduling_proto protoreflect.FileDescriptor

const file_scheduling_v1_scheduling_proto_rawDesc = "" +
	"\n" +
	"\x1escheduling/v1/scheduling.proto\x12\rscheduling.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x03\n" +
	"\vAppointment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x17\n" +
	"\aslot_id\x18\x04 \x01(\tR\x06slotId\x125\n" +
	"\bstart_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .scheduling.v1.AppointmentStatusR\x06status\x12/\n" +
	"\x13prepayment_required\x18\b \x01(\bR\x12prepaymentRequired\x12@\n" +
	"\rrefund_policy\x18\t \x01(\x0e2\x1b.scheduling.v1.RefundPolicyR\frefundPolicy\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb1\x01\n" +
	"\x0fBookSlotRequest\x12\x17\n" +
	"\aslot_id\x18\x01 \x01(\tR\x06slotId\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12(\n" +
	"\x10family_member_id\x18\x04 \x01(\tR\x0efamilyMemberId\x12\x1f\n" +
	"\vintake_json\x18\x05 \x01(\tR\n" +
	"intakeJson\"P\n" +
	"\x10BookSlotResponse\x12<\n" +
	"\vappointment\x18\x01 \x01(\v2\x1a.scheduling.v1.AppointmentR\vappointment\"\xa9\x01\n" +
	"\x18CancelAppointmentRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x03 \x01(\tR\tactorRole\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x14\n" +
	"\x05force\x18\x05 \x01(\bR\x05force\"\xc2\x01\n" +
	"\x19CancelAppointmentResponse\x12<\n" +
	"\vappointment\x18\x01 \x01(\v2\x1a.scheduling.v1.AppointmentR\vappointment\x12@\n" +
	"\rrefund_policy\x18\x02 \x01(\x0e2\x1b.scheduling.v1.RefundPolicyR\frefundPolicy\x12%\n" +
	"\x0erefund_percent\x18\x03 \x01(\x05R\rrefundPercent\"x\n" +
	"\x15GetAppointmentRequest\x12%\n" +
	"\x0eappointment_id\x18\x01 \x01(\tR\rappointmentId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_role\x18\x03 \x01(\tR\tactorRole\"V\n" +
	"\x16GetAppointmentResponse\x12<\n" +
	"\vappointment\x18\x01 \x01(\v2\x1a.scheduling.v1.AppointmentR\vappointment*\xe5\x01\n" +
	"\x11AppointmentStatus\x12\"\n" +
	"\x1eAPPOINTMENT_STATUS_UNSPECIFIED\x10\x00\x12&\n" +
	"\"APPOINTMENT_STATUS_PENDING_PAYMENT\x10\x01\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CONFIRMED\x10\x02\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_CANCELLED\x10\x03\x12 \n" +
	"\x1cAPPOINTMENT_STATUS_COMPLETED\x10\x04\x12\x1e\n" +
	"\x1aAPPOINTMENT_STATUS_NO_SHOW\x10\x05*x\n" +
	"\fRefundPolicy\x12\x1d\n" +
	"\x19REFUND_POLICY_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REFUND_POLICY_FULL\x10\x01\x12\x19\n" +
	"\x15REFUND_POLICY_PARTIAL\x10\x02\x12\x16\n" +
	"\x12REFUND_POLICY_NONE\x10\x032\xa7\x02\n" +
	"\x11SchedulingService\x12K\n" +
	"\bBookSlot\x12\x1e.scheduling.v1.BookSlotRequest\x1a\x1f.scheduling.v1.BookSlotResponse\x12f\n" +
	"\x11CancelAppointment\x12'.scheduling.v1.CancelAppointmentRequest\x1a(.scheduling.v1.CancelAppointmentResponse\x12]\n" +
	"\x0eGetAppointment\x12$.scheduling.v1.GetAppointmentRequest\x1a%.scheduling.v1.GetAppointmentResponseB0Z.telemed/internal/pb/scheduling/v1;schedulingv1b\x06proto3"

var (
	file_scheduling_v1_scheduling_proto_rawDescOnce sync.Once
	file_scheduling_v1_scheduling_proto_rawDescData []byte
)

func file_scheduling_v1_scheduling_proto_rawDescGZIP() []byte {
	file_scheduling_v1_scheduling_proto_rawDescOnce.Do(func() {
		file_scheduling_v1_scheduling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduling_v1_scheduling_proto_rawDesc), len(file_scheduling_v1_scheduling_proto_rawDesc)))
	})
	return file_scheduling_v1_scheduling_proto_rawDescData
}

var file_scheduling_v1_scheduling_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scheduling_v1_scheduling_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scheduling_v1_scheduling_proto_goTypes = []any{
	(AppointmentStatus)(0),            // 0: scheduling.v1.AppointmentStatus
	(RefundPolicy)(0),                 // 1: scheduling.v1.RefundPolicy
	(*Appointment)(nil),               // 2: scheduling.v1.Appointment
	(*BookSlotRequest)(nil),           // 3: scheduling.v1.BookSlotRequest
	(*BookSlotResponse)(nil),          // 4: scheduling.v1.BookSlotResponse
	(*CancelAppointmentRequest)(nil),  // 5: scheduling.v1.CancelAppointmentRequest
	(*CancelAppointmentResponse)(nil), // 6: scheduling.v1.CancelAppointmentResponse
	(*GetAppointmentRequest)(nil),     // 7: scheduling.v1.GetAppointmentRequest
	(*GetAppointmentResponse)(nil),    // 8: scheduling.v1.GetAppointmentResponse
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_scheduling_v1_scheduling_proto_depIdxs = []int32{
	9,  // 0: scheduling.v1.Appointment.start_at:type_name -> google.protobuf.Timestamp
	9,  // 1: scheduling.v1.Appointment.end_at:type_name -> google.protobuf.Timestamp
	0,  // 2: scheduling.v1.Appointment.status:type_name -> scheduling.v1.AppointmentStatus
	1,  // 3: scheduling.v1.Appointment.refund_policy:type_name -> scheduling.v1.RefundPolicy
	9,  // 4: scheduling.v1.Appointment.created_at:type_name -> google.protobuf.Timestamp
	2,  // 5: scheduling.v1.BookSlotResponse.appointment:type_name -> scheduling.v1.Appointment
	2,  // 6: scheduling.v1.CancelAppointmentResponse.appointment:type_name -> scheduling.v1.Appointment
	1,  // 7: scheduling.v1.CancelAppointmentResponse.refund_policy:type_name -> scheduling.v1.RefundPolicy
	2,  // 8: scheduling.v1.GetAppointmentResponse.appointment:type_name -> scheduling.v1.Appointment
	3,  // 9: scheduling.v1.SchedulingService.BookSlot:input_type -> scheduling.v1.BookSlotRequest
	5,  // 10: scheduling.v1.SchedulingService.CancelAppointment:input_type -> scheduling.v1.CancelAppointmentRequest
	7,  // 11: scheduling.v1.SchedulingService.GetAppointment:input_type -> scheduling.v1.GetAppointmentRequest
	4,  // 12: scheduling.v1.SchedulingService.BookSlot:output_type -> scheduling.v1.BookSlotResponse
	6,  // 13: scheduling.v1.SchedulingService.CancelAppointment:output_type -> scheduling.v1.CancelAppointmentResponse
	8,  // 14: scheduling.v1.SchedulingService.GetAppointment:output_type -> scheduling.v1.GetAppointmentResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_scheduling_v1_scheduling_proto_init() }
func file_scheduling_v1_scheduling_proto_init() {
	if File_scheduling_v1_scheduling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduling_v1_scheduling_proto_rawDesc), len(file_scheduling_v1_scheduling_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scheduling_v1_scheduling_proto_goTypes,
		DependencyIndexes: file_scheduling_v1_scheduling_proto_depIdxs,
		EnumInfos:         file_scheduling_v1_scheduling_proto_enumTypes,
		MessageInfos:      file_scheduling_v1_scheduling_proto_msgTypes,
	}.Build()
	File_scheduling_v1_scheduling_proto = out.File
	file_scheduling_v1_scheduling_proto_goTypes = nil
	file_scheduling_v1_scheduling_proto_depIdxs = nil
}
