// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: scheduling/v1/scheduling.proto

// The internal, service-to-service scheduling API.
//
// It exists for the calls that sit on a user-facing latency budget and must not
// pay for JSON and HTTP/1.1: payment-service confirming a booking, and
// consultation-service resolving an appointment five minutes before a video
// call. Anything a patient's phone talks to goes over REST.

package schedulingv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SchedulingService_BookSlot_FullMethodName          = "/scheduling.v1.SchedulingService/BookSlot"
	SchedulingService_CancelAppointment_FullMethodName = "/scheduling.v1.SchedulingService/CancelAppointment"
	SchedulingService_GetAppointment_FullMethodName    = "/scheduling.v1.SchedulingService/GetAppointment"
)

// SchedulingServiceClient is the client API for SchedulingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulingServiceClient interface {
	// BookSlot books an available slot for a patient. It is the same code path
	// the REST endpoint uses, with the same three-layer race protection.
	BookSlot(ctx context.Context, in *BookSlotRequest, opts ...grpc.CallOption) (*BookSlotResponse, error)
	// CancelAppointment releases a slot and returns the refund policy the
	// cancellation earned. The caller must not re-derive that policy.
	CancelAppointment(ctx context.Context, in *CancelAppointmentRequest, opts ...grpc.CallOption) (*CancelAppointmentResponse, error)
	// GetAppointment reads one appointment.
	GetAppointment(ctx context.Context, in *GetAppointmentRequest, opts ...grpc.CallOption) (*GetAppointmentResponse, error)
}

type schedulingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulingServiceClient(cc grpc.ClientConnInterface) SchedulingServiceClient {
	return &schedulingServiceClient{cc}
}

func (c *schedulingServiceClient) BookSlot(ctx context.Context, in *BookSlotRequest, opts ...grpc.CallOption) (*BookSlotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookSlotResponse)
	err := c.cc.Invoke(ctx, SchedulingService_BookSlot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) CancelAppointment(ctx context.Context, in *CancelAppointmentRequest, opts ...grpc.CallOption) (*CancelAppointmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAppointmentResponse)
	err := c.cc.Invoke(ctx, SchedulingService_CancelAppointment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedulingServiceClient) GetAppointment(ctx context.Context, in *GetAppointmentRequest, opts ...grpc.CallOption) (*GetAppointmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppointmentResponse)
	err := c.cc.Invoke(ctx, SchedulingService_GetAppointment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulingServiceServer is the server API for SchedulingService service.
// All implementations must embed UnimplementedSchedulingServiceServer
// for forward compatibility.
type SchedulingServiceServer interface {
	// BookSlot books an available slot for a patient. It is the same code path
	// the REST endpoint uses, with the same three-layer race protection.
	BookSlot(context.Context, *BookSlotRequest) (*BookSlotResponse, error)
	// CancelAppointment releases a slot and returns the refund policy the
	// cancellation earned. The caller must not re-derive that policy.
	CancelAppointment(context.Context, *CancelAppointmentRequest) (*CancelAppointmentResponse, error)
	// GetAppointment reads one appointment.
	GetAppointment(context.Context, *GetAppointmentRequest) (*GetAppointmentResponse, error)
	mustEmbedUnimplementedSchedulingServiceServer()
}

// UnimplementedSchedulingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSchedulingServiceServer struct{}

func (UnimplementedSchedulingServiceServer) BookSlot(context.Context, *BookSlotRequest) (*BookSlotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BookSlot not implemented")
}
func (UnimplementedSchedulingServiceServer) CancelAppointment(context.Context, *CancelAppointmentRequest) (*CancelAppointmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelAppointment not implemented")
}
func (UnimplementedSchedulingServiceServer) GetAppointment(context.Context, *GetAppointmentRequest) (*GetAppointmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppointment not implemented")
}
func (UnimplementedSchedulingServiceServer) mustEmbedUnimplementedSchedulingServiceServer() {}
func (UnimplementedSchedulingServiceServer) testEmbeddedByValue()                           {}

// UnsafeSchedulingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SchedulingServiceServer will
// result in compilation errors.
type UnsafeSchedulingServiceServer interface {
	mustEmbedUnimplementedSchedulingServiceServer()
}

func RegisterSchedulingServiceServer(s grpc.ServiceRegistrar, srv SchedulingServiceServer) {
	// If the following call panics, it indicates UnimplementedSchedulingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SchedulingService_ServiceDesc, srv)
}

func _SchedulingService_BookSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).BookSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_BookSlot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).BookSlot(ctx, req.(*BookSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_CancelAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAppointmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).CancelAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_CancelAppointment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).CancelAppointment(ctx, req.(*CancelAppointmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedulingService_GetAppointment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppointmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulingServiceServer).GetAppointment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SchedulingService_GetAppointment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulingServiceServer).GetAppointment(ctx, req.(*GetAppointmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SchedulingService_ServiceDesc is the grpc.ServiceDesc for SchedulingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SchedulingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduling.v1.SchedulingService",
	HandlerType: (*SchedulingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BookSlot",
			Handler:    _SchedulingService_BookSlot_Handler,
		},
		{
			MethodName: "CancelAppointment",
			Handler:    _SchedulingService_CancelAppointment_Handler,
		},
		{
			MethodName: "GetAppointment",
			Handler:    _SchedulingService_GetAppointment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduling/v1/scheduling.proto",
}
